/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.etg.profile.CompanyProfile');

goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.etg.profile.CompanyProfile = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.etg.profile.CompanyProfile, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.etg.profile.CompanyProfile.displayName = 'proto.etg.profile.CompanyProfile';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.etg.profile.CompanyProfile.prototype.toObject = function(opt_includeInstance) {
  return proto.etg.profile.CompanyProfile.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.etg.profile.CompanyProfile} msg The msg instance to transform.
 * @return {!Object}
 */
proto.etg.profile.CompanyProfile.toObject = function(includeInstance, msg) {
  var f, obj = {
    companyId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    orgCo: jspb.Message.getFieldWithDefault(msg, 2, ""),
    socialCreditCode: jspb.Message.getFieldWithDefault(msg, 3, ""),
    name: jspb.Message.getFieldWithDefault(msg, 4, ""),
    contactName: jspb.Message.getFieldWithDefault(msg, 5, ""),
    contactMobile: jspb.Message.getFieldWithDefault(msg, 6, ""),
    lawManName: jspb.Message.getFieldWithDefault(msg, 7, ""),
    lawManMobile: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional string company_id = 1;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getCompanyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setCompanyId = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string org_co = 2;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getOrgCo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setOrgCo = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string social_credit_code = 3;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getSocialCreditCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setSocialCreditCode = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string name = 4;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setName = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string contact_name = 5;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getContactName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setContactName = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string contact_mobile = 6;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getContactMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setContactMobile = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string law_man_name = 7;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getLawManName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setLawManName = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string law_man_mobile = 8;
 * @return {string}
 */
proto.etg.profile.CompanyProfile.prototype.getLawManMobile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.etg.profile.CompanyProfile.prototype.setLawManMobile = function(value) {
  jspb.Message.setField(this, 8, value);
};


