/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.etg.auth.LoginReply');

goog.require('jspb.Message');
goog.require('proto.etg.profile.CompanyProfile');
goog.require('proto.etg.profile.UserProfile');
goog.require('proto.google.protobuf.Timestamp');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.etg.auth.LoginReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.etg.auth.LoginReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.etg.auth.LoginReply.displayName = 'proto.etg.auth.LoginReply';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.etg.auth.LoginReply.prototype.toObject = function(opt_includeInstance) {
  return proto.etg.auth.LoginReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.etg.auth.LoginReply} msg The msg instance to transform.
 * @return {!Object}
 */
proto.etg.auth.LoginReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    isSuccessful: jspb.Message.getFieldWithDefault(msg, 1, false),
    message: jspb.Message.getFieldWithDefault(msg, 2, ""),
    accessToken: jspb.Message.getFieldWithDefault(msg, 3, ""),
    timestampExpireAt: (f = msg.getTimestampExpireAt()) && proto.google.protobuf.Timestamp.toObject(includeInstance, f),
    user: (f = msg.getUser()) && proto.etg.profile.UserProfile.toObject(includeInstance, f),
    company: (f = msg.getCompany()) && proto.etg.profile.CompanyProfile.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional bool is_successful = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.etg.auth.LoginReply.prototype.getIsSuccessful = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.etg.auth.LoginReply.prototype.setIsSuccessful = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string message = 2;
 * @return {string}
 */
proto.etg.auth.LoginReply.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.etg.auth.LoginReply.prototype.setMessage = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string access_token = 3;
 * @return {string}
 */
proto.etg.auth.LoginReply.prototype.getAccessToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.etg.auth.LoginReply.prototype.setAccessToken = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional google.protobuf.Timestamp timestamp_expire_at = 4;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.etg.auth.LoginReply.prototype.getTimestampExpireAt = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, proto.google.protobuf.Timestamp, 4));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.etg.auth.LoginReply.prototype.setTimestampExpireAt = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.etg.auth.LoginReply.prototype.clearTimestampExpireAt = function() {
  this.setTimestampExpireAt(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.etg.auth.LoginReply.prototype.hasTimestampExpireAt = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional etg.profile.UserProfile user = 5;
 * @return {?proto.etg.profile.UserProfile}
 */
proto.etg.auth.LoginReply.prototype.getUser = function() {
  return /** @type{?proto.etg.profile.UserProfile} */ (
    jspb.Message.getWrapperField(this, proto.etg.profile.UserProfile, 5));
};


/** @param {?proto.etg.profile.UserProfile|undefined} value */
proto.etg.auth.LoginReply.prototype.setUser = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.etg.auth.LoginReply.prototype.clearUser = function() {
  this.setUser(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.etg.auth.LoginReply.prototype.hasUser = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional etg.profile.CompanyProfile company = 6;
 * @return {?proto.etg.profile.CompanyProfile}
 */
proto.etg.auth.LoginReply.prototype.getCompany = function() {
  return /** @type{?proto.etg.profile.CompanyProfile} */ (
    jspb.Message.getWrapperField(this, proto.etg.profile.CompanyProfile, 6));
};


/** @param {?proto.etg.profile.CompanyProfile|undefined} value */
proto.etg.auth.LoginReply.prototype.setCompany = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.etg.auth.LoginReply.prototype.clearCompany = function() {
  this.setCompany(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.etg.auth.LoginReply.prototype.hasCompany = function() {
  return jspb.Message.getField(this, 6) != null;
};


