/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.etg.auth.LoginRequest');

goog.require('jspb.Message');

goog.forwardDeclare('proto.etg.auth.LoginType');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.etg.auth.LoginRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.etg.auth.LoginRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.etg.auth.LoginRequest.displayName = 'proto.etg.auth.LoginRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.etg.auth.LoginRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.etg.auth.LoginRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.etg.auth.LoginRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.etg.auth.LoginRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    loginType: jspb.Message.getFieldWithDefault(msg, 1, 0),
    email: jspb.Message.getFieldWithDefault(msg, 2, ""),
    hashedPasswd: jspb.Message.getFieldWithDefault(msg, 3, ""),
    companyId: jspb.Message.getFieldWithDefault(msg, 4, ""),
    token: jspb.Message.getFieldWithDefault(msg, 5, ""),
    accessToken: jspb.Message.getFieldWithDefault(msg, 6, ""),
    captchaId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    captcha: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * optional LoginType login_type = 1;
 * @return {!proto.etg.auth.LoginType}
 */
proto.etg.auth.LoginRequest.prototype.getLoginType = function() {
  return /** @type {!proto.etg.auth.LoginType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.etg.auth.LoginType} value */
proto.etg.auth.LoginRequest.prototype.setLoginType = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string email = 2;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setEmail = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string hashed_passwd = 3;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getHashedPasswd = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setHashedPasswd = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string company_id = 4;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getCompanyId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setCompanyId = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string token = 5;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setToken = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string access_token = 6;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getAccessToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setAccessToken = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string captcha_id = 7;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getCaptchaId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setCaptchaId = function(value) {
  jspb.Message.setField(this, 7, value);
};


/**
 * optional string captcha = 8;
 * @return {string}
 */
proto.etg.auth.LoginRequest.prototype.getCaptcha = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.etg.auth.LoginRequest.prototype.setCaptcha = function(value) {
  jspb.Message.setField(this, 8, value);
};


