// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Etg.Profile {

  /// <summary>Holder for reflection information generated from profile.proto</summary>
  public static partial class ProfileReflection {

    #region Descriptor
    /// <summary>File descriptor for profile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wcm9maWxlLnByb3RvEgtldGcucHJvZmlsZSJXCgtVc2VyUHJvZmlsZRIM",
            "CgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEg4KBm1vYmlsZRgDIAEoCRIb",
            "ChNhdXRoZW50aWNhdGlvbl9tb2RlGAQgASgNIroBCg5Db21wYW55UHJvZmls",
            "ZRISCgpjb21wYW55X2lkGAEgASgJEg4KBm9yZ19jbxgCIAEoCRIaChJzb2Np",
            "YWxfY3JlZGl0X2NvZGUYAyABKAkSDAoEbmFtZRgEIAEoCRIUCgxjb250YWN0",
            "X25hbWUYBSABKAkSFgoOY29udGFjdF9tb2JpbGUYBiABKAkSFAoMbGF3X21h",
            "bl9uYW1lGAcgASgJEhYKDmxhd19tYW5fbW9iaWxlGAggASgJImwKFFVwZGF0",
            "ZVByb2ZpbGVSZXF1ZXN0EhQKDGFjY2Vzc190b2tlbhgBIAEoCRIMCgRuYW1l",
            "GAIgASgJEg0KBWVtYWlsGAMgASgJEg4KBm1vYmlsZRgEIAEoCRIRCgluZXdQ",
            "YXNzd2QYBSABKAkiPwoVVXBkYXRlUHJvZmlsZVJlc3BvbnNlEhUKDWlzX3N1",
            "Y2Nlc3NmdWwYASABKAgSDwoHbWVzc2FnZRgCIAEoCTJjCgdQcm9maWxlElgK",
            "DVVwZGF0ZVByb2ZpbGUSIS5ldGcucHJvZmlsZS5VcGRhdGVQcm9maWxlUmVx",
            "dWVzdBoiLmV0Zy5wcm9maWxlLlVwZGF0ZVByb2ZpbGVSZXNwb25zZSIAQi0K",
            "C2V0Zy5wcm9maWxlQghFdGdQcm90b1ABogIDRVRHqgILRXRnLlByb2ZpbGVi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.UserProfile), global::Etg.Profile.UserProfile.Parser, new[]{ "Name", "Email", "Mobile", "AuthenticationMode" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.CompanyProfile), global::Etg.Profile.CompanyProfile.Parser, new[]{ "CompanyId", "OrgCo", "SocialCreditCode", "Name", "ContactName", "ContactMobile", "LawManName", "LawManMobile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.UpdateProfileRequest), global::Etg.Profile.UpdateProfileRequest.Parser, new[]{ "AccessToken", "Name", "Email", "Mobile", "NewPasswd" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.UpdateProfileResponse), global::Etg.Profile.UpdateProfileResponse.Parser, new[]{ "IsSuccessful", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserProfile : pb::IMessage<UserProfile> {
    private static readonly pb::MessageParser<UserProfile> _parser = new pb::MessageParser<UserProfile>(() => new UserProfile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserProfile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile(UserProfile other) : this() {
      name_ = other.name_;
      email_ = other.email_;
      mobile_ = other.mobile_;
      authenticationMode_ = other.authenticationMode_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile Clone() {
      return new UserProfile(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mobile" field.</summary>
    public const int MobileFieldNumber = 3;
    private string mobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mobile {
      get { return mobile_; }
      set {
        mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "authentication_mode" field.</summary>
    public const int AuthenticationModeFieldNumber = 4;
    private uint authenticationMode_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint AuthenticationMode {
      get { return authenticationMode_; }
      set {
        authenticationMode_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserProfile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserProfile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (Mobile != other.Mobile) return false;
      if (AuthenticationMode != other.AuthenticationMode) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
      if (AuthenticationMode != 0) hash ^= AuthenticationMode.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (Mobile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mobile);
      }
      if (AuthenticationMode != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AuthenticationMode);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Mobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
      }
      if (AuthenticationMode != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AuthenticationMode);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserProfile other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Mobile.Length != 0) {
        Mobile = other.Mobile;
      }
      if (other.AuthenticationMode != 0) {
        AuthenticationMode = other.AuthenticationMode;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 26: {
            Mobile = input.ReadString();
            break;
          }
          case 32: {
            AuthenticationMode = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CompanyProfile : pb::IMessage<CompanyProfile> {
    private static readonly pb::MessageParser<CompanyProfile> _parser = new pb::MessageParser<CompanyProfile>(() => new CompanyProfile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CompanyProfile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile(CompanyProfile other) : this() {
      companyId_ = other.companyId_;
      orgCo_ = other.orgCo_;
      socialCreditCode_ = other.socialCreditCode_;
      name_ = other.name_;
      contactName_ = other.contactName_;
      contactMobile_ = other.contactMobile_;
      lawManName_ = other.lawManName_;
      lawManMobile_ = other.lawManMobile_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile Clone() {
      return new CompanyProfile(this);
    }

    /// <summary>Field number for the "company_id" field.</summary>
    public const int CompanyIdFieldNumber = 1;
    private string companyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CompanyId {
      get { return companyId_; }
      set {
        companyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "org_co" field.</summary>
    public const int OrgCoFieldNumber = 2;
    private string orgCo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrgCo {
      get { return orgCo_; }
      set {
        orgCo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "social_credit_code" field.</summary>
    public const int SocialCreditCodeFieldNumber = 3;
    private string socialCreditCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SocialCreditCode {
      get { return socialCreditCode_; }
      set {
        socialCreditCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_name" field.</summary>
    public const int ContactNameFieldNumber = 5;
    private string contactName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactName {
      get { return contactName_; }
      set {
        contactName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_mobile" field.</summary>
    public const int ContactMobileFieldNumber = 6;
    private string contactMobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactMobile {
      get { return contactMobile_; }
      set {
        contactMobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "law_man_name" field.</summary>
    public const int LawManNameFieldNumber = 7;
    private string lawManName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LawManName {
      get { return lawManName_; }
      set {
        lawManName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "law_man_mobile" field.</summary>
    public const int LawManMobileFieldNumber = 8;
    private string lawManMobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LawManMobile {
      get { return lawManMobile_; }
      set {
        lawManMobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CompanyProfile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CompanyProfile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CompanyId != other.CompanyId) return false;
      if (OrgCo != other.OrgCo) return false;
      if (SocialCreditCode != other.SocialCreditCode) return false;
      if (Name != other.Name) return false;
      if (ContactName != other.ContactName) return false;
      if (ContactMobile != other.ContactMobile) return false;
      if (LawManName != other.LawManName) return false;
      if (LawManMobile != other.LawManMobile) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CompanyId.Length != 0) hash ^= CompanyId.GetHashCode();
      if (OrgCo.Length != 0) hash ^= OrgCo.GetHashCode();
      if (SocialCreditCode.Length != 0) hash ^= SocialCreditCode.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ContactName.Length != 0) hash ^= ContactName.GetHashCode();
      if (ContactMobile.Length != 0) hash ^= ContactMobile.GetHashCode();
      if (LawManName.Length != 0) hash ^= LawManName.GetHashCode();
      if (LawManMobile.Length != 0) hash ^= LawManMobile.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CompanyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CompanyId);
      }
      if (OrgCo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrgCo);
      }
      if (SocialCreditCode.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SocialCreditCode);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (ContactName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ContactName);
      }
      if (ContactMobile.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ContactMobile);
      }
      if (LawManName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LawManName);
      }
      if (LawManMobile.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LawManMobile);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CompanyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CompanyId);
      }
      if (OrgCo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrgCo);
      }
      if (SocialCreditCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SocialCreditCode);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ContactName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactName);
      }
      if (ContactMobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactMobile);
      }
      if (LawManName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LawManName);
      }
      if (LawManMobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LawManMobile);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CompanyProfile other) {
      if (other == null) {
        return;
      }
      if (other.CompanyId.Length != 0) {
        CompanyId = other.CompanyId;
      }
      if (other.OrgCo.Length != 0) {
        OrgCo = other.OrgCo;
      }
      if (other.SocialCreditCode.Length != 0) {
        SocialCreditCode = other.SocialCreditCode;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ContactName.Length != 0) {
        ContactName = other.ContactName;
      }
      if (other.ContactMobile.Length != 0) {
        ContactMobile = other.ContactMobile;
      }
      if (other.LawManName.Length != 0) {
        LawManName = other.LawManName;
      }
      if (other.LawManMobile.Length != 0) {
        LawManMobile = other.LawManMobile;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            CompanyId = input.ReadString();
            break;
          }
          case 18: {
            OrgCo = input.ReadString();
            break;
          }
          case 26: {
            SocialCreditCode = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            ContactName = input.ReadString();
            break;
          }
          case 50: {
            ContactMobile = input.ReadString();
            break;
          }
          case 58: {
            LawManName = input.ReadString();
            break;
          }
          case 66: {
            LawManMobile = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateProfileRequest : pb::IMessage<UpdateProfileRequest> {
    private static readonly pb::MessageParser<UpdateProfileRequest> _parser = new pb::MessageParser<UpdateProfileRequest>(() => new UpdateProfileRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateProfileRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest(UpdateProfileRequest other) : this() {
      accessToken_ = other.accessToken_;
      name_ = other.name_;
      email_ = other.email_;
      mobile_ = other.mobile_;
      newPasswd_ = other.newPasswd_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileRequest Clone() {
      return new UpdateProfileRequest(this);
    }

    /// <summary>Field number for the "access_token" field.</summary>
    public const int AccessTokenFieldNumber = 1;
    private string accessToken_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string AccessToken {
      get { return accessToken_; }
      set {
        accessToken_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 3;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mobile" field.</summary>
    public const int MobileFieldNumber = 4;
    private string mobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mobile {
      get { return mobile_; }
      set {
        mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "newPasswd" field.</summary>
    public const int NewPasswdFieldNumber = 5;
    private string newPasswd_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string NewPasswd {
      get { return newPasswd_; }
      set {
        newPasswd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateProfileRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateProfileRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccessToken != other.AccessToken) return false;
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (Mobile != other.Mobile) return false;
      if (NewPasswd != other.NewPasswd) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AccessToken.Length != 0) hash ^= AccessToken.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
      if (NewPasswd.Length != 0) hash ^= NewPasswd.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AccessToken.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccessToken);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Mobile.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Mobile);
      }
      if (NewPasswd.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(NewPasswd);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AccessToken.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccessToken);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Mobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
      }
      if (NewPasswd.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NewPasswd);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateProfileRequest other) {
      if (other == null) {
        return;
      }
      if (other.AccessToken.Length != 0) {
        AccessToken = other.AccessToken;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Mobile.Length != 0) {
        Mobile = other.Mobile;
      }
      if (other.NewPasswd.Length != 0) {
        NewPasswd = other.NewPasswd;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            AccessToken = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Mobile = input.ReadString();
            break;
          }
          case 42: {
            NewPasswd = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UpdateProfileResponse : pb::IMessage<UpdateProfileResponse> {
    private static readonly pb::MessageParser<UpdateProfileResponse> _parser = new pb::MessageParser<UpdateProfileResponse>(() => new UpdateProfileResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateProfileResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileResponse(UpdateProfileResponse other) : this() {
      isSuccessful_ = other.isSuccessful_;
      message_ = other.message_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateProfileResponse Clone() {
      return new UpdateProfileResponse(this);
    }

    /// <summary>Field number for the "is_successful" field.</summary>
    public const int IsSuccessfulFieldNumber = 1;
    private bool isSuccessful_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool IsSuccessful {
      get { return isSuccessful_; }
      set {
        isSuccessful_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateProfileResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateProfileResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IsSuccessful != other.IsSuccessful) return false;
      if (Message != other.Message) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IsSuccessful != false) hash ^= IsSuccessful.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IsSuccessful != false) {
        output.WriteRawTag(8);
        output.WriteBool(IsSuccessful);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IsSuccessful != false) {
        size += 1 + 1;
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateProfileResponse other) {
      if (other == null) {
        return;
      }
      if (other.IsSuccessful != false) {
        IsSuccessful = other.IsSuccessful;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            IsSuccessful = input.ReadBool();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
