// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Etg.Profile {

  /// <summary>Holder for reflection information generated from profile.proto</summary>
  public static partial class ProfileReflection {

    #region Descriptor
    /// <summary>File descriptor for profile.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProfileReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wcm9maWxlLnByb3RvEgtldGcucHJvZmlsZSI6CgtVc2VyUHJvZmlsZRIM",
            "CgRuYW1lGAEgASgJEg0KBWVtYWlsGAIgASgJEg4KBm1vYmlsZRgDIAEoCSK6",
            "AQoOQ29tcGFueVByb2ZpbGUSEgoKY29tcGFueV9pZBgBIAEoCRIOCgZvcmdf",
            "Y28YAiABKAkSGgoSc29jaWFsX2NyZWRpdF9jb2RlGAMgASgJEgwKBG5hbWUY",
            "BCABKAkSFAoMY29udGFjdF9uYW1lGAUgASgJEhYKDmNvbnRhY3RfbW9iaWxl",
            "GAYgASgJEhQKDGxhd19tYW5fbmFtZRgHIAEoCRIWCg5sYXdfbWFuX21vYmls",
            "ZRgIIAEoCWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.UserProfile), global::Etg.Profile.UserProfile.Parser, new[]{ "Name", "Email", "Mobile" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Profile.CompanyProfile), global::Etg.Profile.CompanyProfile.Parser, new[]{ "CompanyId", "OrgCo", "SocialCreditCode", "Name", "ContactName", "ContactMobile", "LawManName", "LawManMobile" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class UserProfile : pb::IMessage<UserProfile> {
    private static readonly pb::MessageParser<UserProfile> _parser = new pb::MessageParser<UserProfile>(() => new UserProfile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UserProfile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile(UserProfile other) : this() {
      name_ = other.name_;
      email_ = other.email_;
      mobile_ = other.mobile_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UserProfile Clone() {
      return new UserProfile(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 2;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "mobile" field.</summary>
    public const int MobileFieldNumber = 3;
    private string mobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Mobile {
      get { return mobile_; }
      set {
        mobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UserProfile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UserProfile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Email != other.Email) return false;
      if (Mobile != other.Mobile) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Mobile.Length != 0) hash ^= Mobile.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Email);
      }
      if (Mobile.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Mobile);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Mobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Mobile);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UserProfile other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Mobile.Length != 0) {
        Mobile = other.Mobile;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Email = input.ReadString();
            break;
          }
          case 26: {
            Mobile = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CompanyProfile : pb::IMessage<CompanyProfile> {
    private static readonly pb::MessageParser<CompanyProfile> _parser = new pb::MessageParser<CompanyProfile>(() => new CompanyProfile());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CompanyProfile> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Profile.ProfileReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile(CompanyProfile other) : this() {
      companyId_ = other.companyId_;
      orgCo_ = other.orgCo_;
      socialCreditCode_ = other.socialCreditCode_;
      name_ = other.name_;
      contactName_ = other.contactName_;
      contactMobile_ = other.contactMobile_;
      lawManName_ = other.lawManName_;
      lawManMobile_ = other.lawManMobile_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CompanyProfile Clone() {
      return new CompanyProfile(this);
    }

    /// <summary>Field number for the "company_id" field.</summary>
    public const int CompanyIdFieldNumber = 1;
    private string companyId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CompanyId {
      get { return companyId_; }
      set {
        companyId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "org_co" field.</summary>
    public const int OrgCoFieldNumber = 2;
    private string orgCo_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string OrgCo {
      get { return orgCo_; }
      set {
        orgCo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "social_credit_code" field.</summary>
    public const int SocialCreditCodeFieldNumber = 3;
    private string socialCreditCode_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SocialCreditCode {
      get { return socialCreditCode_; }
      set {
        socialCreditCode_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_name" field.</summary>
    public const int ContactNameFieldNumber = 5;
    private string contactName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactName {
      get { return contactName_; }
      set {
        contactName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "contact_mobile" field.</summary>
    public const int ContactMobileFieldNumber = 6;
    private string contactMobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ContactMobile {
      get { return contactMobile_; }
      set {
        contactMobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "law_man_name" field.</summary>
    public const int LawManNameFieldNumber = 7;
    private string lawManName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LawManName {
      get { return lawManName_; }
      set {
        lawManName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "law_man_mobile" field.</summary>
    public const int LawManMobileFieldNumber = 8;
    private string lawManMobile_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string LawManMobile {
      get { return lawManMobile_; }
      set {
        lawManMobile_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CompanyProfile);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CompanyProfile other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CompanyId != other.CompanyId) return false;
      if (OrgCo != other.OrgCo) return false;
      if (SocialCreditCode != other.SocialCreditCode) return false;
      if (Name != other.Name) return false;
      if (ContactName != other.ContactName) return false;
      if (ContactMobile != other.ContactMobile) return false;
      if (LawManName != other.LawManName) return false;
      if (LawManMobile != other.LawManMobile) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (CompanyId.Length != 0) hash ^= CompanyId.GetHashCode();
      if (OrgCo.Length != 0) hash ^= OrgCo.GetHashCode();
      if (SocialCreditCode.Length != 0) hash ^= SocialCreditCode.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ContactName.Length != 0) hash ^= ContactName.GetHashCode();
      if (ContactMobile.Length != 0) hash ^= ContactMobile.GetHashCode();
      if (LawManName.Length != 0) hash ^= LawManName.GetHashCode();
      if (LawManMobile.Length != 0) hash ^= LawManMobile.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (CompanyId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(CompanyId);
      }
      if (OrgCo.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(OrgCo);
      }
      if (SocialCreditCode.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SocialCreditCode);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (ContactName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ContactName);
      }
      if (ContactMobile.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(ContactMobile);
      }
      if (LawManName.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(LawManName);
      }
      if (LawManMobile.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(LawManMobile);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (CompanyId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CompanyId);
      }
      if (OrgCo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OrgCo);
      }
      if (SocialCreditCode.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SocialCreditCode);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ContactName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactName);
      }
      if (ContactMobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ContactMobile);
      }
      if (LawManName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LawManName);
      }
      if (LawManMobile.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LawManMobile);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CompanyProfile other) {
      if (other == null) {
        return;
      }
      if (other.CompanyId.Length != 0) {
        CompanyId = other.CompanyId;
      }
      if (other.OrgCo.Length != 0) {
        OrgCo = other.OrgCo;
      }
      if (other.SocialCreditCode.Length != 0) {
        SocialCreditCode = other.SocialCreditCode;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ContactName.Length != 0) {
        ContactName = other.ContactName;
      }
      if (other.ContactMobile.Length != 0) {
        ContactMobile = other.ContactMobile;
      }
      if (other.LawManName.Length != 0) {
        LawManName = other.LawManName;
      }
      if (other.LawManMobile.Length != 0) {
        LawManMobile = other.LawManMobile;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            CompanyId = input.ReadString();
            break;
          }
          case 18: {
            OrgCo = input.ReadString();
            break;
          }
          case 26: {
            SocialCreditCode = input.ReadString();
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            ContactName = input.ReadString();
            break;
          }
          case 50: {
            ContactMobile = input.ReadString();
            break;
          }
          case 58: {
            LawManName = input.ReadString();
            break;
          }
          case 66: {
            LawManMobile = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
