// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Etg.Service {

  /// <summary>Holder for reflection information generated from service.proto</summary>
  public static partial class ServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1zZXJ2aWNlLnByb3RvEgtldGcuc2VydmljZRoNcHJvZmlsZS5wcm90bxoK",
            "YXV0aC5wcm90bzI/CgRBdXRoEjcKBUxvZ2luEhYuZXRnLmF1dGguTG9naW5S",
            "ZXF1ZXN0GhQuZXRnLmF1dGguTG9naW5SZXBseSIAQi0KC2V0Zy5zZXJ2aWNl",
            "QghFdGdQcm90b1ABogIDRVRHqgILRXRnLlNlcnZpY2VQAFABYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Etg.Profile.ProfileReflection.Descriptor, global::Etg.Auth.AuthReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
