// Code generated by protoc-gen-go.
// source: entry_data.proto
// DO NOT EDIT!

/*
Package etg_data_entry is a generated protocol buffer package.

It is generated from these files:
	entry_data.proto

It has these top-level messages:
	GetEntryStatusRequest
	GetEntryStatusResponse
	GetYDTEntryDataRequest
	GetYDTEntryDataResponse
*/
package etg_data_entry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetEntryStatusRequest struct {
	EntryId string `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
}

func (m *GetEntryStatusRequest) Reset()                    { *m = GetEntryStatusRequest{} }
func (m *GetEntryStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetEntryStatusRequest) ProtoMessage()               {}
func (*GetEntryStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetEntryStatusRequest) GetEntryId() string {
	if m != nil {
		return m.EntryId
	}
	return ""
}

type GetEntryStatusResponse struct {
	EntryId     string                     `protobuf:"bytes,1,opt,name=entry_id,json=entryId" json:"entry_id,omitempty"`
	StatusText  string                     `protobuf:"bytes,2,opt,name=status_text,json=statusText" json:"status_text,omitempty"`
	DeclareDate *google_protobuf.Timestamp `protobuf:"bytes,3,opt,name=declare_date,json=declareDate" json:"declare_date,omitempty"`
}

func (m *GetEntryStatusResponse) Reset()                    { *m = GetEntryStatusResponse{} }
func (m *GetEntryStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*GetEntryStatusResponse) ProtoMessage()               {}
func (*GetEntryStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetEntryStatusResponse) GetEntryId() string {
	if m != nil {
		return m.EntryId
	}
	return ""
}

func (m *GetEntryStatusResponse) GetStatusText() string {
	if m != nil {
		return m.StatusText
	}
	return ""
}

func (m *GetEntryStatusResponse) GetDeclareDate() *google_protobuf.Timestamp {
	if m != nil {
		return m.DeclareDate
	}
	return nil
}

type GetYDTEntryDataRequest struct {
	DateFrom *google_protobuf.Timestamp `protobuf:"bytes,1,opt,name=date_from,json=dateFrom" json:"date_from,omitempty"`
}

func (m *GetYDTEntryDataRequest) Reset()                    { *m = GetYDTEntryDataRequest{} }
func (m *GetYDTEntryDataRequest) String() string            { return proto.CompactTextString(m) }
func (*GetYDTEntryDataRequest) ProtoMessage()               {}
func (*GetYDTEntryDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetYDTEntryDataRequest) GetDateFrom() *google_protobuf.Timestamp {
	if m != nil {
		return m.DateFrom
	}
	return nil
}

type GetYDTEntryDataResponse struct {
	FileName string `protobuf:"bytes,1,opt,name=file_name,json=fileName" json:"file_name,omitempty"`
	Data     []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *GetYDTEntryDataResponse) Reset()                    { *m = GetYDTEntryDataResponse{} }
func (m *GetYDTEntryDataResponse) String() string            { return proto.CompactTextString(m) }
func (*GetYDTEntryDataResponse) ProtoMessage()               {}
func (*GetYDTEntryDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetYDTEntryDataResponse) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *GetYDTEntryDataResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*GetEntryStatusRequest)(nil), "etg.data.entry.GetEntryStatusRequest")
	proto.RegisterType((*GetEntryStatusResponse)(nil), "etg.data.entry.GetEntryStatusResponse")
	proto.RegisterType((*GetYDTEntryDataRequest)(nil), "etg.data.entry.GetYDTEntryDataRequest")
	proto.RegisterType((*GetYDTEntryDataResponse)(nil), "etg.data.entry.GetYDTEntryDataResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for EntryDataService service

type EntryDataServiceClient interface {
	GetEntryStatus(ctx context.Context, opts ...grpc.CallOption) (EntryDataService_GetEntryStatusClient, error)
	GetYDTEntryDataFrom(ctx context.Context, in *GetYDTEntryDataRequest, opts ...grpc.CallOption) (EntryDataService_GetYDTEntryDataFromClient, error)
	GetYDTEntryDataAt(ctx context.Context, in *GetYDTEntryDataRequest, opts ...grpc.CallOption) (*GetYDTEntryDataResponse, error)
}

type entryDataServiceClient struct {
	cc *grpc.ClientConn
}

func NewEntryDataServiceClient(cc *grpc.ClientConn) EntryDataServiceClient {
	return &entryDataServiceClient{cc}
}

func (c *entryDataServiceClient) GetEntryStatus(ctx context.Context, opts ...grpc.CallOption) (EntryDataService_GetEntryStatusClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EntryDataService_serviceDesc.Streams[0], c.cc, "/etg.data.entry.EntryDataService/GetEntryStatus", opts...)
	if err != nil {
		return nil, err
	}
	x := &entryDataServiceGetEntryStatusClient{stream}
	return x, nil
}

type EntryDataService_GetEntryStatusClient interface {
	Send(*GetEntryStatusRequest) error
	Recv() (*GetEntryStatusResponse, error)
	grpc.ClientStream
}

type entryDataServiceGetEntryStatusClient struct {
	grpc.ClientStream
}

func (x *entryDataServiceGetEntryStatusClient) Send(m *GetEntryStatusRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *entryDataServiceGetEntryStatusClient) Recv() (*GetEntryStatusResponse, error) {
	m := new(GetEntryStatusResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *entryDataServiceClient) GetYDTEntryDataFrom(ctx context.Context, in *GetYDTEntryDataRequest, opts ...grpc.CallOption) (EntryDataService_GetYDTEntryDataFromClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_EntryDataService_serviceDesc.Streams[1], c.cc, "/etg.data.entry.EntryDataService/GetYDTEntryDataFrom", opts...)
	if err != nil {
		return nil, err
	}
	x := &entryDataServiceGetYDTEntryDataFromClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EntryDataService_GetYDTEntryDataFromClient interface {
	Recv() (*GetYDTEntryDataResponse, error)
	grpc.ClientStream
}

type entryDataServiceGetYDTEntryDataFromClient struct {
	grpc.ClientStream
}

func (x *entryDataServiceGetYDTEntryDataFromClient) Recv() (*GetYDTEntryDataResponse, error) {
	m := new(GetYDTEntryDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *entryDataServiceClient) GetYDTEntryDataAt(ctx context.Context, in *GetYDTEntryDataRequest, opts ...grpc.CallOption) (*GetYDTEntryDataResponse, error) {
	out := new(GetYDTEntryDataResponse)
	err := grpc.Invoke(ctx, "/etg.data.entry.EntryDataService/GetYDTEntryDataAt", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for EntryDataService service

type EntryDataServiceServer interface {
	GetEntryStatus(EntryDataService_GetEntryStatusServer) error
	GetYDTEntryDataFrom(*GetYDTEntryDataRequest, EntryDataService_GetYDTEntryDataFromServer) error
	GetYDTEntryDataAt(context.Context, *GetYDTEntryDataRequest) (*GetYDTEntryDataResponse, error)
}

func RegisterEntryDataServiceServer(s *grpc.Server, srv EntryDataServiceServer) {
	s.RegisterService(&_EntryDataService_serviceDesc, srv)
}

func _EntryDataService_GetEntryStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EntryDataServiceServer).GetEntryStatus(&entryDataServiceGetEntryStatusServer{stream})
}

type EntryDataService_GetEntryStatusServer interface {
	Send(*GetEntryStatusResponse) error
	Recv() (*GetEntryStatusRequest, error)
	grpc.ServerStream
}

type entryDataServiceGetEntryStatusServer struct {
	grpc.ServerStream
}

func (x *entryDataServiceGetEntryStatusServer) Send(m *GetEntryStatusResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *entryDataServiceGetEntryStatusServer) Recv() (*GetEntryStatusRequest, error) {
	m := new(GetEntryStatusRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _EntryDataService_GetYDTEntryDataFrom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetYDTEntryDataRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EntryDataServiceServer).GetYDTEntryDataFrom(m, &entryDataServiceGetYDTEntryDataFromServer{stream})
}

type EntryDataService_GetYDTEntryDataFromServer interface {
	Send(*GetYDTEntryDataResponse) error
	grpc.ServerStream
}

type entryDataServiceGetYDTEntryDataFromServer struct {
	grpc.ServerStream
}

func (x *entryDataServiceGetYDTEntryDataFromServer) Send(m *GetYDTEntryDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EntryDataService_GetYDTEntryDataAt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetYDTEntryDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntryDataServiceServer).GetYDTEntryDataAt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/etg.data.entry.EntryDataService/GetYDTEntryDataAt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntryDataServiceServer).GetYDTEntryDataAt(ctx, req.(*GetYDTEntryDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntryDataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "etg.data.entry.EntryDataService",
	HandlerType: (*EntryDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetYDTEntryDataAt",
			Handler:    _EntryDataService_GetYDTEntryDataAt_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEntryStatus",
			Handler:       _EntryDataService_GetEntryStatus_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetYDTEntryDataFrom",
			Handler:       _EntryDataService_GetYDTEntryDataFrom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "entry_data.proto",
}

func init() { proto.RegisterFile("entry_data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 383 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x92, 0x41, 0x8f, 0xd2, 0x40,
	0x14, 0xc7, 0x9d, 0x62, 0xb4, 0x3c, 0x08, 0xc1, 0x31, 0x2a, 0xd6, 0x03, 0xa4, 0x89, 0xca, 0x69,
	0x20, 0x70, 0xf0, 0xe4, 0x41, 0x42, 0x25, 0x7a, 0x30, 0x58, 0x7a, 0xf1, 0xd4, 0x0c, 0xf4, 0xb5,
	0xa9, 0xa1, 0x14, 0xdb, 0x87, 0x61, 0x3f, 0xc7, 0x7e, 0x83, 0x3d, 0xee, 0x77, 0xd9, 0xef, 0xb4,
	0x99, 0x29, 0xdd, 0x84, 0x2e, 0x81, 0xd3, 0xde, 0x3a, 0xf3, 0xfe, 0xef, 0x3f, 0xef, 0xf7, 0xfe,
	0x85, 0x36, 0x6e, 0x28, 0xbb, 0xf2, 0x03, 0x49, 0x52, 0x6c, 0xb3, 0x94, 0x52, 0xde, 0x42, 0x8a,
	0x84, 0x3e, 0xeb, 0x92, 0xd5, 0x8d, 0xd2, 0x34, 0x5a, 0xe3, 0x40, 0x57, 0x97, 0xbb, 0x70, 0x40,
	0x71, 0x82, 0x39, 0xc9, 0x64, 0x5b, 0x34, 0xd8, 0x23, 0x78, 0x33, 0x43, 0x72, 0x94, 0x78, 0x41,
	0x92, 0x76, 0xb9, 0x8b, 0xff, 0x76, 0x98, 0x13, 0x7f, 0x0f, 0x66, 0xe1, 0x1e, 0x07, 0x1d, 0xd6,
	0x63, 0xfd, 0xba, 0xfb, 0x52, 0x9f, 0x7f, 0x04, 0xf6, 0x35, 0x83, 0xb7, 0xd5, 0xa6, 0x7c, 0x9b,
	0x6e, 0x72, 0x3c, 0xd3, 0xc5, 0xbb, 0xd0, 0xc8, 0xb5, 0xd8, 0x27, 0xdc, 0x53, 0xc7, 0xd0, 0x55,
	0x28, 0xae, 0x3c, 0xdc, 0x13, 0xff, 0x0a, 0xcd, 0x00, 0x57, 0x6b, 0x99, 0xa1, 0x22, 0xc2, 0x4e,
	0xad, 0xc7, 0xfa, 0x8d, 0x91, 0x25, 0x0a, 0x04, 0x51, 0x22, 0x08, 0xaf, 0x44, 0x70, 0x1b, 0x07,
	0xfd, 0x54, 0x12, 0xda, 0xbf, 0xf5, 0x50, 0x7f, 0xa6, 0x9e, 0x9e, 0x6b, 0x2a, 0x49, 0x96, 0x28,
	0x5f, 0xa0, 0xae, 0x0c, 0xfd, 0x30, 0x4b, 0x13, 0x3d, 0xd5, 0x79, 0x57, 0x53, 0x89, 0xbf, 0x67,
	0x69, 0x62, 0xff, 0x84, 0x77, 0x8f, 0x2c, 0x0f, 0xa0, 0x1f, 0xa0, 0x1e, 0xc6, 0x6b, 0xf4, 0x37,
	0x32, 0xc1, 0x03, 0xa9, 0xa9, 0x2e, 0x7e, 0xc9, 0x04, 0x39, 0x87, 0xe7, 0x2a, 0x03, 0xcd, 0xd8,
	0x74, 0xf5, 0xf7, 0xe8, 0xce, 0x80, 0xf6, 0x83, 0xcd, 0x02, 0xb3, 0xff, 0xf1, 0x0a, 0x39, 0x42,
	0xeb, 0x78, 0x91, 0xfc, 0xa3, 0x38, 0x4e, 0x50, 0x9c, 0x4c, 0xc7, 0xfa, 0x74, 0x49, 0x56, 0x8c,
	0x69, 0x3f, 0xeb, 0xb3, 0x21, 0xe3, 0x7f, 0xe1, 0x75, 0x85, 0x43, 0xe1, 0xf1, 0x53, 0x26, 0x27,
	0xf6, 0x67, 0x7d, 0xbe, 0xa8, 0x2b, 0x5f, 0x1b, 0x32, 0x1e, 0xc2, 0xab, 0x4a, 0xf9, 0x1b, 0x3d,
	0xc1, 0x4b, 0x93, 0x31, 0x54, 0xfe, 0xf5, 0x89, 0xe9, 0x50, 0x34, 0x57, 0x71, 0xce, 0xd9, 0x8d,
	0x51, 0x73, 0xbc, 0xd9, 0xad, 0xd1, 0x72, 0x28, 0x12, 0xaa, 0x51, 0x68, 0x8b, 0xe5, 0x0b, 0x1d,
	0xf7, 0xf8, 0x3e, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x83, 0x95, 0xac, 0x39, 0x03, 0x00, 0x00,
}
