// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

 #import "Profile.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class CompanyProfile;
@class GPBTimestamp;
@class UserProfile;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ETGLoginType

typedef GPB_ENUM(ETGLoginType) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ETGLoginType_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ETGLoginType_Email = 0,
  ETGLoginType_CompanyId = 1,
  ETGLoginType_AccessToken = 2,
};

GPBEnumDescriptor *ETGLoginType_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ETGLoginType_IsValidValue(int32_t value);

#pragma mark - ETGAuthRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ETGAuthRoot : GPBRootObject
@end

#pragma mark - ETGLoginRequest

typedef GPB_ENUM(ETGLoginRequest_FieldNumber) {
  ETGLoginRequest_FieldNumber_LoginType = 1,
  ETGLoginRequest_FieldNumber_Email = 2,
  ETGLoginRequest_FieldNumber_HashedPasswd = 3,
  ETGLoginRequest_FieldNumber_CompanyId = 4,
  ETGLoginRequest_FieldNumber_Token = 5,
  ETGLoginRequest_FieldNumber_AccessToken = 6,
  ETGLoginRequest_FieldNumber_CaptchaId = 7,
  ETGLoginRequest_FieldNumber_Captcha = 8,
};

@interface ETGLoginRequest : GPBMessage

@property(nonatomic, readwrite) ETGLoginType loginType;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashedPasswd;

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyId;

/** token sent to contact's mobile */
@property(nonatomic, readwrite, copy, null_resettable) NSString *token;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, copy, null_resettable) NSString *captchaId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *captcha;

@end

/**
 * Fetches the raw value of a @c ETGLoginRequest's @c loginType property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ETGLoginRequest_LoginType_RawValue(ETGLoginRequest *message);
/**
 * Sets the raw value of an @c ETGLoginRequest's @c loginType property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetETGLoginRequest_LoginType_RawValue(ETGLoginRequest *message, int32_t value);

#pragma mark - ETGLoginReply

typedef GPB_ENUM(ETGLoginReply_FieldNumber) {
  ETGLoginReply_FieldNumber_IsSuccessful = 1,
  ETGLoginReply_FieldNumber_Message = 2,
  ETGLoginReply_FieldNumber_AccessToken = 3,
  ETGLoginReply_FieldNumber_TimestampExpireAt = 4,
  ETGLoginReply_FieldNumber_User = 5,
  ETGLoginReply_FieldNumber_Company = 6,
};

@interface ETGLoginReply : GPBMessage

@property(nonatomic, readwrite) BOOL isSuccessful;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite, copy, null_resettable) NSString *accessToken;

@property(nonatomic, readwrite, strong, null_resettable) GPBTimestamp *timestampExpireAt;
/** Test to see if @c timestampExpireAt has been set. */
@property(nonatomic, readwrite) BOOL hasTimestampExpireAt;

@property(nonatomic, readwrite, strong, null_resettable) UserProfile *user;
/** Test to see if @c user has been set. */
@property(nonatomic, readwrite) BOOL hasUser;

@property(nonatomic, readwrite, strong, null_resettable) CompanyProfile *company;
/** Test to see if @c company has been set. */
@property(nonatomic, readwrite) BOOL hasCompany;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
