// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ProfileRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface ProfileRoot : GPBRootObject
@end

#pragma mark - UserProfile

typedef GPB_ENUM(UserProfile_FieldNumber) {
  UserProfile_FieldNumber_Name = 1,
  UserProfile_FieldNumber_Email = 2,
  UserProfile_FieldNumber_Mobile = 3,
};

@interface UserProfile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *email;

@property(nonatomic, readwrite, copy, null_resettable) NSString *mobile;

@end

#pragma mark - CompanyProfile

typedef GPB_ENUM(CompanyProfile_FieldNumber) {
  CompanyProfile_FieldNumber_CompanyId = 1,
  CompanyProfile_FieldNumber_OrgCo = 2,
  CompanyProfile_FieldNumber_SocialCreditCode = 3,
  CompanyProfile_FieldNumber_Name = 4,
  CompanyProfile_FieldNumber_ContactName = 5,
  CompanyProfile_FieldNumber_ContactMobile = 6,
  CompanyProfile_FieldNumber_LawManName = 7,
  CompanyProfile_FieldNumber_LawManMobile = 8,
};

@interface CompanyProfile : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *companyId;

@property(nonatomic, readwrite, copy, null_resettable) NSString *orgCo;

@property(nonatomic, readwrite, copy, null_resettable) NSString *socialCreditCode;

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contactName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *contactMobile;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lawManName;

@property(nonatomic, readwrite, copy, null_resettable) NSString *lawManMobile;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
