// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "Profile.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - ProfileRoot

@implementation ProfileRoot

// No extensions in the file and no imports, so no need to generate
// +extensionRegistry.

@end

#pragma mark - ProfileRoot_FileDescriptor

static GPBFileDescriptor *ProfileRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"etg.profile"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UserProfile

@implementation UserProfile

@dynamic name;
@dynamic email;
@dynamic mobile;

typedef struct UserProfile__storage_ {
  uint32_t _has_storage_[1];
  NSString *name;
  NSString *email;
  NSString *mobile;
} UserProfile__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = UserProfile_FieldNumber_Name,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UserProfile__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "email",
        .dataTypeSpecific.className = NULL,
        .number = UserProfile_FieldNumber_Email,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(UserProfile__storage_, email),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "mobile",
        .dataTypeSpecific.className = NULL,
        .number = UserProfile_FieldNumber_Mobile,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(UserProfile__storage_, mobile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UserProfile class]
                                     rootClass:[ProfileRoot class]
                                          file:ProfileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UserProfile__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

#pragma mark - CompanyProfile

@implementation CompanyProfile

@dynamic companyId;
@dynamic orgCo;
@dynamic socialCreditCode;
@dynamic name;
@dynamic contactName;
@dynamic contactMobile;
@dynamic lawManName;
@dynamic lawManMobile;

typedef struct CompanyProfile__storage_ {
  uint32_t _has_storage_[1];
  NSString *companyId;
  NSString *orgCo;
  NSString *socialCreditCode;
  NSString *name;
  NSString *contactName;
  NSString *contactMobile;
  NSString *lawManName;
  NSString *lawManMobile;
} CompanyProfile__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "companyId",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_CompanyId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, companyId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "orgCo",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_OrgCo,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, orgCo),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "socialCreditCode",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_SocialCreditCode,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, socialCreditCode),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "name",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_Name,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, name),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contactName",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_ContactName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, contactName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "contactMobile",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_ContactMobile,
        .hasIndex = 5,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, contactMobile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lawManName",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_LawManName,
        .hasIndex = 6,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, lawManName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "lawManMobile",
        .dataTypeSpecific.className = NULL,
        .number = CompanyProfile_FieldNumber_LawManMobile,
        .hasIndex = 7,
        .offset = (uint32_t)offsetof(CompanyProfile__storage_, lawManMobile),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[CompanyProfile class]
                                     rootClass:[ProfileRoot class]
                                          file:ProfileRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(CompanyProfile__storage_)
                                         flags:GPBDescriptorInitializationFlag_None];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
