// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package etg.profile;

public final class Profile {
  private Profile() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:etg.profile.UserProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string email = 2;</code>
     */
    java.lang.String getEmail();
    /**
     * <code>optional string email = 2;</code>
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>optional string mobile = 3;</code>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 3;</code>
     */
    com.google.protobuf.ByteString
        getMobileBytes();
  }
  /**
   * Protobuf type {@code etg.profile.UserProfile}
   */
  public  static final class UserProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:etg.profile.UserProfile)
      UserProfileOrBuilder {
    // Use UserProfile.newBuilder() to construct.
    private UserProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserProfile() {
      name_ = "";
      email_ = "";
      mobile_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              mobile_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return etg.profile.Profile.internal_static_etg_profile_UserProfile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return etg.profile.Profile.internal_static_etg_profile_UserProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              etg.profile.Profile.UserProfile.class, etg.profile.Profile.UserProfile.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 2;
    private volatile java.lang.Object email_;
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 3;
    private volatile java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 3;</code>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string mobile = 3;</code>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, mobile_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, mobile_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof etg.profile.Profile.UserProfile)) {
        return super.equals(obj);
      }
      etg.profile.Profile.UserProfile other = (etg.profile.Profile.UserProfile) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getEmail()
          .equals(other.getEmail());
      result = result && getMobile()
          .equals(other.getMobile());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getMobile().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static etg.profile.Profile.UserProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static etg.profile.Profile.UserProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static etg.profile.Profile.UserProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static etg.profile.Profile.UserProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static etg.profile.Profile.UserProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.UserProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static etg.profile.Profile.UserProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.UserProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static etg.profile.Profile.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.UserProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(etg.profile.Profile.UserProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code etg.profile.UserProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:etg.profile.UserProfile)
        etg.profile.Profile.UserProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return etg.profile.Profile.internal_static_etg_profile_UserProfile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return etg.profile.Profile.internal_static_etg_profile_UserProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                etg.profile.Profile.UserProfile.class, etg.profile.Profile.UserProfile.Builder.class);
      }

      // Construct using etg.profile.Profile.UserProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        name_ = "";

        email_ = "";

        mobile_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return etg.profile.Profile.internal_static_etg_profile_UserProfile_descriptor;
      }

      public etg.profile.Profile.UserProfile getDefaultInstanceForType() {
        return etg.profile.Profile.UserProfile.getDefaultInstance();
      }

      public etg.profile.Profile.UserProfile build() {
        etg.profile.Profile.UserProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public etg.profile.Profile.UserProfile buildPartial() {
        etg.profile.Profile.UserProfile result = new etg.profile.Profile.UserProfile(this);
        result.name_ = name_;
        result.email_ = email_;
        result.mobile_ = mobile_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof etg.profile.Profile.UserProfile) {
          return mergeFrom((etg.profile.Profile.UserProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(etg.profile.Profile.UserProfile other) {
        if (other == etg.profile.Profile.UserProfile.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        etg.profile.Profile.UserProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (etg.profile.Profile.UserProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>optional string email = 2;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string email = 2;</code>
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 3;</code>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 3;</code>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 3;</code>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 3;</code>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 3;</code>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mobile_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:etg.profile.UserProfile)
    }

    // @@protoc_insertion_point(class_scope:etg.profile.UserProfile)
    private static final etg.profile.Profile.UserProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new etg.profile.Profile.UserProfile();
    }

    public static etg.profile.Profile.UserProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProfile>
        PARSER = new com.google.protobuf.AbstractParser<UserProfile>() {
      public UserProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserProfile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProfile> getParserForType() {
      return PARSER;
    }

    public etg.profile.Profile.UserProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CompanyProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:etg.profile.CompanyProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string company_id = 1;</code>
     */
    java.lang.String getCompanyId();
    /**
     * <code>optional string company_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getCompanyIdBytes();

    /**
     * <code>optional string org_co = 2;</code>
     */
    java.lang.String getOrgCo();
    /**
     * <code>optional string org_co = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrgCoBytes();

    /**
     * <code>optional string social_credit_code = 3;</code>
     */
    java.lang.String getSocialCreditCode();
    /**
     * <code>optional string social_credit_code = 3;</code>
     */
    com.google.protobuf.ByteString
        getSocialCreditCodeBytes();

    /**
     * <code>optional string name = 4;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 4;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string contact_name = 5;</code>
     */
    java.lang.String getContactName();
    /**
     * <code>optional string contact_name = 5;</code>
     */
    com.google.protobuf.ByteString
        getContactNameBytes();

    /**
     * <code>optional string contact_mobile = 6;</code>
     */
    java.lang.String getContactMobile();
    /**
     * <code>optional string contact_mobile = 6;</code>
     */
    com.google.protobuf.ByteString
        getContactMobileBytes();

    /**
     * <code>optional string law_man_name = 7;</code>
     */
    java.lang.String getLawManName();
    /**
     * <code>optional string law_man_name = 7;</code>
     */
    com.google.protobuf.ByteString
        getLawManNameBytes();

    /**
     * <code>optional string law_man_mobile = 8;</code>
     */
    java.lang.String getLawManMobile();
    /**
     * <code>optional string law_man_mobile = 8;</code>
     */
    com.google.protobuf.ByteString
        getLawManMobileBytes();
  }
  /**
   * Protobuf type {@code etg.profile.CompanyProfile}
   */
  public  static final class CompanyProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:etg.profile.CompanyProfile)
      CompanyProfileOrBuilder {
    // Use CompanyProfile.newBuilder() to construct.
    private CompanyProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CompanyProfile() {
      companyId_ = "";
      orgCo_ = "";
      socialCreditCode_ = "";
      name_ = "";
      contactName_ = "";
      contactMobile_ = "";
      lawManName_ = "";
      lawManMobile_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CompanyProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              companyId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              orgCo_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              socialCreditCode_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              contactName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              contactMobile_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              lawManName_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              lawManMobile_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return etg.profile.Profile.internal_static_etg_profile_CompanyProfile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return etg.profile.Profile.internal_static_etg_profile_CompanyProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              etg.profile.Profile.CompanyProfile.class, etg.profile.Profile.CompanyProfile.Builder.class);
    }

    public static final int COMPANY_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object companyId_;
    /**
     * <code>optional string company_id = 1;</code>
     */
    public java.lang.String getCompanyId() {
      java.lang.Object ref = companyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string company_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyIdBytes() {
      java.lang.Object ref = companyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORG_CO_FIELD_NUMBER = 2;
    private volatile java.lang.Object orgCo_;
    /**
     * <code>optional string org_co = 2;</code>
     */
    public java.lang.String getOrgCo() {
      java.lang.Object ref = orgCo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        orgCo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string org_co = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrgCoBytes() {
      java.lang.Object ref = orgCo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        orgCo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOCIAL_CREDIT_CODE_FIELD_NUMBER = 3;
    private volatile java.lang.Object socialCreditCode_;
    /**
     * <code>optional string social_credit_code = 3;</code>
     */
    public java.lang.String getSocialCreditCode() {
      java.lang.Object ref = socialCreditCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        socialCreditCode_ = s;
        return s;
      }
    }
    /**
     * <code>optional string social_credit_code = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSocialCreditCodeBytes() {
      java.lang.Object ref = socialCreditCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        socialCreditCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 4;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_NAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object contactName_;
    /**
     * <code>optional string contact_name = 5;</code>
     */
    public java.lang.String getContactName() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contact_name = 5;</code>
     */
    public com.google.protobuf.ByteString
        getContactNameBytes() {
      java.lang.Object ref = contactName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_MOBILE_FIELD_NUMBER = 6;
    private volatile java.lang.Object contactMobile_;
    /**
     * <code>optional string contact_mobile = 6;</code>
     */
    public java.lang.String getContactMobile() {
      java.lang.Object ref = contactMobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        contactMobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string contact_mobile = 6;</code>
     */
    public com.google.protobuf.ByteString
        getContactMobileBytes() {
      java.lang.Object ref = contactMobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        contactMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAW_MAN_NAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object lawManName_;
    /**
     * <code>optional string law_man_name = 7;</code>
     */
    public java.lang.String getLawManName() {
      java.lang.Object ref = lawManName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lawManName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string law_man_name = 7;</code>
     */
    public com.google.protobuf.ByteString
        getLawManNameBytes() {
      java.lang.Object ref = lawManName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lawManName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAW_MAN_MOBILE_FIELD_NUMBER = 8;
    private volatile java.lang.Object lawManMobile_;
    /**
     * <code>optional string law_man_mobile = 8;</code>
     */
    public java.lang.String getLawManMobile() {
      java.lang.Object ref = lawManMobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lawManMobile_ = s;
        return s;
      }
    }
    /**
     * <code>optional string law_man_mobile = 8;</code>
     */
    public com.google.protobuf.ByteString
        getLawManMobileBytes() {
      java.lang.Object ref = lawManMobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lawManMobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCompanyIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, companyId_);
      }
      if (!getOrgCoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orgCo_);
      }
      if (!getSocialCreditCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, socialCreditCode_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, name_);
      }
      if (!getContactNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, contactName_);
      }
      if (!getContactMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, contactMobile_);
      }
      if (!getLawManNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, lawManName_);
      }
      if (!getLawManMobileBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, lawManMobile_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCompanyIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, companyId_);
      }
      if (!getOrgCoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orgCo_);
      }
      if (!getSocialCreditCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, socialCreditCode_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, name_);
      }
      if (!getContactNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, contactName_);
      }
      if (!getContactMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, contactMobile_);
      }
      if (!getLawManNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, lawManName_);
      }
      if (!getLawManMobileBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, lawManMobile_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof etg.profile.Profile.CompanyProfile)) {
        return super.equals(obj);
      }
      etg.profile.Profile.CompanyProfile other = (etg.profile.Profile.CompanyProfile) obj;

      boolean result = true;
      result = result && getCompanyId()
          .equals(other.getCompanyId());
      result = result && getOrgCo()
          .equals(other.getOrgCo());
      result = result && getSocialCreditCode()
          .equals(other.getSocialCreditCode());
      result = result && getName()
          .equals(other.getName());
      result = result && getContactName()
          .equals(other.getContactName());
      result = result && getContactMobile()
          .equals(other.getContactMobile());
      result = result && getLawManName()
          .equals(other.getLawManName());
      result = result && getLawManMobile()
          .equals(other.getLawManMobile());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
      hash = (53 * hash) + getCompanyId().hashCode();
      hash = (37 * hash) + ORG_CO_FIELD_NUMBER;
      hash = (53 * hash) + getOrgCo().hashCode();
      hash = (37 * hash) + SOCIAL_CREDIT_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getSocialCreditCode().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CONTACT_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getContactName().hashCode();
      hash = (37 * hash) + CONTACT_MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getContactMobile().hashCode();
      hash = (37 * hash) + LAW_MAN_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLawManName().hashCode();
      hash = (37 * hash) + LAW_MAN_MOBILE_FIELD_NUMBER;
      hash = (53 * hash) + getLawManMobile().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static etg.profile.Profile.CompanyProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static etg.profile.Profile.CompanyProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.CompanyProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static etg.profile.Profile.CompanyProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(etg.profile.Profile.CompanyProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code etg.profile.CompanyProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:etg.profile.CompanyProfile)
        etg.profile.Profile.CompanyProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return etg.profile.Profile.internal_static_etg_profile_CompanyProfile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return etg.profile.Profile.internal_static_etg_profile_CompanyProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                etg.profile.Profile.CompanyProfile.class, etg.profile.Profile.CompanyProfile.Builder.class);
      }

      // Construct using etg.profile.Profile.CompanyProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        companyId_ = "";

        orgCo_ = "";

        socialCreditCode_ = "";

        name_ = "";

        contactName_ = "";

        contactMobile_ = "";

        lawManName_ = "";

        lawManMobile_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return etg.profile.Profile.internal_static_etg_profile_CompanyProfile_descriptor;
      }

      public etg.profile.Profile.CompanyProfile getDefaultInstanceForType() {
        return etg.profile.Profile.CompanyProfile.getDefaultInstance();
      }

      public etg.profile.Profile.CompanyProfile build() {
        etg.profile.Profile.CompanyProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public etg.profile.Profile.CompanyProfile buildPartial() {
        etg.profile.Profile.CompanyProfile result = new etg.profile.Profile.CompanyProfile(this);
        result.companyId_ = companyId_;
        result.orgCo_ = orgCo_;
        result.socialCreditCode_ = socialCreditCode_;
        result.name_ = name_;
        result.contactName_ = contactName_;
        result.contactMobile_ = contactMobile_;
        result.lawManName_ = lawManName_;
        result.lawManMobile_ = lawManMobile_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof etg.profile.Profile.CompanyProfile) {
          return mergeFrom((etg.profile.Profile.CompanyProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(etg.profile.Profile.CompanyProfile other) {
        if (other == etg.profile.Profile.CompanyProfile.getDefaultInstance()) return this;
        if (!other.getCompanyId().isEmpty()) {
          companyId_ = other.companyId_;
          onChanged();
        }
        if (!other.getOrgCo().isEmpty()) {
          orgCo_ = other.orgCo_;
          onChanged();
        }
        if (!other.getSocialCreditCode().isEmpty()) {
          socialCreditCode_ = other.socialCreditCode_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getContactName().isEmpty()) {
          contactName_ = other.contactName_;
          onChanged();
        }
        if (!other.getContactMobile().isEmpty()) {
          contactMobile_ = other.contactMobile_;
          onChanged();
        }
        if (!other.getLawManName().isEmpty()) {
          lawManName_ = other.lawManName_;
          onChanged();
        }
        if (!other.getLawManMobile().isEmpty()) {
          lawManMobile_ = other.lawManMobile_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        etg.profile.Profile.CompanyProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (etg.profile.Profile.CompanyProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object companyId_ = "";
      /**
       * <code>optional string company_id = 1;</code>
       */
      public java.lang.String getCompanyId() {
        java.lang.Object ref = companyId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          companyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string company_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getCompanyIdBytes() {
        java.lang.Object ref = companyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          companyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string company_id = 1;</code>
       */
      public Builder setCompanyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        companyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_id = 1;</code>
       */
      public Builder clearCompanyId() {
        
        companyId_ = getDefaultInstance().getCompanyId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string company_id = 1;</code>
       */
      public Builder setCompanyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        companyId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object orgCo_ = "";
      /**
       * <code>optional string org_co = 2;</code>
       */
      public java.lang.String getOrgCo() {
        java.lang.Object ref = orgCo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          orgCo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string org_co = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrgCoBytes() {
        java.lang.Object ref = orgCo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          orgCo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string org_co = 2;</code>
       */
      public Builder setOrgCo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orgCo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string org_co = 2;</code>
       */
      public Builder clearOrgCo() {
        
        orgCo_ = getDefaultInstance().getOrgCo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string org_co = 2;</code>
       */
      public Builder setOrgCoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orgCo_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object socialCreditCode_ = "";
      /**
       * <code>optional string social_credit_code = 3;</code>
       */
      public java.lang.String getSocialCreditCode() {
        java.lang.Object ref = socialCreditCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          socialCreditCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string social_credit_code = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSocialCreditCodeBytes() {
        java.lang.Object ref = socialCreditCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          socialCreditCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string social_credit_code = 3;</code>
       */
      public Builder setSocialCreditCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        socialCreditCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string social_credit_code = 3;</code>
       */
      public Builder clearSocialCreditCode() {
        
        socialCreditCode_ = getDefaultInstance().getSocialCreditCode();
        onChanged();
        return this;
      }
      /**
       * <code>optional string social_credit_code = 3;</code>
       */
      public Builder setSocialCreditCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        socialCreditCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 4;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 4;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contactName_ = "";
      /**
       * <code>optional string contact_name = 5;</code>
       */
      public java.lang.String getContactName() {
        java.lang.Object ref = contactName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contact_name = 5;</code>
       */
      public com.google.protobuf.ByteString
          getContactNameBytes() {
        java.lang.Object ref = contactName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contact_name = 5;</code>
       */
      public Builder setContactName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contact_name = 5;</code>
       */
      public Builder clearContactName() {
        
        contactName_ = getDefaultInstance().getContactName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contact_name = 5;</code>
       */
      public Builder setContactNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object contactMobile_ = "";
      /**
       * <code>optional string contact_mobile = 6;</code>
       */
      public java.lang.String getContactMobile() {
        java.lang.Object ref = contactMobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          contactMobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string contact_mobile = 6;</code>
       */
      public com.google.protobuf.ByteString
          getContactMobileBytes() {
        java.lang.Object ref = contactMobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          contactMobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string contact_mobile = 6;</code>
       */
      public Builder setContactMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        contactMobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string contact_mobile = 6;</code>
       */
      public Builder clearContactMobile() {
        
        contactMobile_ = getDefaultInstance().getContactMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string contact_mobile = 6;</code>
       */
      public Builder setContactMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        contactMobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lawManName_ = "";
      /**
       * <code>optional string law_man_name = 7;</code>
       */
      public java.lang.String getLawManName() {
        java.lang.Object ref = lawManName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lawManName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string law_man_name = 7;</code>
       */
      public com.google.protobuf.ByteString
          getLawManNameBytes() {
        java.lang.Object ref = lawManName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lawManName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string law_man_name = 7;</code>
       */
      public Builder setLawManName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lawManName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string law_man_name = 7;</code>
       */
      public Builder clearLawManName() {
        
        lawManName_ = getDefaultInstance().getLawManName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string law_man_name = 7;</code>
       */
      public Builder setLawManNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lawManName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lawManMobile_ = "";
      /**
       * <code>optional string law_man_mobile = 8;</code>
       */
      public java.lang.String getLawManMobile() {
        java.lang.Object ref = lawManMobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lawManMobile_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string law_man_mobile = 8;</code>
       */
      public com.google.protobuf.ByteString
          getLawManMobileBytes() {
        java.lang.Object ref = lawManMobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lawManMobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string law_man_mobile = 8;</code>
       */
      public Builder setLawManMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        lawManMobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string law_man_mobile = 8;</code>
       */
      public Builder clearLawManMobile() {
        
        lawManMobile_ = getDefaultInstance().getLawManMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string law_man_mobile = 8;</code>
       */
      public Builder setLawManMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        lawManMobile_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:etg.profile.CompanyProfile)
    }

    // @@protoc_insertion_point(class_scope:etg.profile.CompanyProfile)
    private static final etg.profile.Profile.CompanyProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new etg.profile.Profile.CompanyProfile();
    }

    public static etg.profile.Profile.CompanyProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CompanyProfile>
        PARSER = new com.google.protobuf.AbstractParser<CompanyProfile>() {
      public CompanyProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CompanyProfile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CompanyProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CompanyProfile> getParserForType() {
      return PARSER;
    }

    public etg.profile.Profile.CompanyProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etg_profile_UserProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_etg_profile_UserProfile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etg_profile_CompanyProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_etg_profile_CompanyProfile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rprofile.proto\022\013etg.profile\":\n\013UserProf" +
      "ile\022\014\n\004name\030\001 \001(\t\022\r\n\005email\030\002 \001(\t\022\016\n\006mobi" +
      "le\030\003 \001(\t\"\272\001\n\016CompanyProfile\022\022\n\ncompany_i" +
      "d\030\001 \001(\t\022\016\n\006org_co\030\002 \001(\t\022\032\n\022social_credit" +
      "_code\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\022\024\n\014contact_nam" +
      "e\030\005 \001(\t\022\026\n\016contact_mobile\030\006 \001(\t\022\024\n\014law_m" +
      "an_name\030\007 \001(\t\022\026\n\016law_man_mobile\030\010 \001(\tb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_etg_profile_UserProfile_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_etg_profile_UserProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_etg_profile_UserProfile_descriptor,
        new java.lang.String[] { "Name", "Email", "Mobile", });
    internal_static_etg_profile_CompanyProfile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_etg_profile_CompanyProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_etg_profile_CompanyProfile_descriptor,
        new java.lang.String[] { "CompanyId", "OrgCo", "SocialCreditCode", "Name", "ContactName", "ContactMobile", "LawManName", "LawManMobile", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
