// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entry_data.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Etg.Data.Entry {

  /// <summary>Holder for reflection information generated from entry_data.proto</summary>
  public static partial class EntryDataReflection {

    #region Descriptor
    /// <summary>File descriptor for entry_data.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EntryDataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBlbnRyeV9kYXRhLnByb3RvEg5ldGcuZGF0YS5lbnRyeRofZ29vZ2xlL3By",
            "b3RvYnVmL3RpbWVzdGFtcC5wcm90byIpChVHZXRFbnRyeVN0YXR1c1JlcXVl",
            "c3QSEAoIZW50cnlfaWQYASABKAkicQoWR2V0RW50cnlTdGF0dXNSZXNwb25z",
            "ZRIQCghlbnRyeV9pZBgBIAEoCRITCgtzdGF0dXNfdGV4dBgCIAEoCRIwCgxk",
            "ZWNsYXJlX2RhdGUYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1w",
            "IkcKFkdldFlEVEVudHJ5RGF0YVJlcXVlc3QSLQoJZGF0ZV9mcm9tGAEgASgL",
            "MhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCI6ChdHZXRZRFRFbnRyeURh",
            "dGFSZXNwb25zZRIRCglmaWxlX25hbWUYASABKAkSDAoEZGF0YRgCIAEoDDLN",
            "AgoQRW50cnlEYXRhU2VydmljZRJlCg5HZXRFbnRyeVN0YXR1cxIlLmV0Zy5k",
            "YXRhLmVudHJ5LkdldEVudHJ5U3RhdHVzUmVxdWVzdBomLmV0Zy5kYXRhLmVu",
            "dHJ5LkdldEVudHJ5U3RhdHVzUmVzcG9uc2UiACgBMAESagoTR2V0WURURW50",
            "cnlEYXRhRnJvbRImLmV0Zy5kYXRhLmVudHJ5LkdldFlEVEVudHJ5RGF0YVJl",
            "cXVlc3QaJy5ldGcuZGF0YS5lbnRyeS5HZXRZRFRFbnRyeURhdGFSZXNwb25z",
            "ZSIAMAESZgoRR2V0WURURW50cnlEYXRhQXQSJi5ldGcuZGF0YS5lbnRyeS5H",
            "ZXRZRFRFbnRyeURhdGFSZXF1ZXN0GicuZXRnLmRhdGEuZW50cnkuR2V0WURU",
            "RW50cnlEYXRhUmVzcG9uc2UiAEIzCg5ldGcuZGF0YS5lbnRyeUIIRXRnUHJv",
            "dG9QAaICA0VUR6oCDkV0Zy5EYXRhLkVudHJ5YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Data.Entry.GetEntryStatusRequest), global::Etg.Data.Entry.GetEntryStatusRequest.Parser, new[]{ "EntryId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Data.Entry.GetEntryStatusResponse), global::Etg.Data.Entry.GetEntryStatusResponse.Parser, new[]{ "EntryId", "StatusText", "DeclareDate" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Data.Entry.GetYDTEntryDataRequest), global::Etg.Data.Entry.GetYDTEntryDataRequest.Parser, new[]{ "DateFrom" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Etg.Data.Entry.GetYDTEntryDataResponse), global::Etg.Data.Entry.GetYDTEntryDataResponse.Parser, new[]{ "FileName", "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetEntryStatusRequest : pb::IMessage<GetEntryStatusRequest> {
    private static readonly pb::MessageParser<GetEntryStatusRequest> _parser = new pb::MessageParser<GetEntryStatusRequest>(() => new GetEntryStatusRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetEntryStatusRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Data.Entry.EntryDataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusRequest(GetEntryStatusRequest other) : this() {
      entryId_ = other.entryId_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusRequest Clone() {
      return new GetEntryStatusRequest(this);
    }

    /// <summary>Field number for the "entry_id" field.</summary>
    public const int EntryIdFieldNumber = 1;
    private string entryId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EntryId {
      get { return entryId_; }
      set {
        entryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetEntryStatusRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetEntryStatusRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntryId != other.EntryId) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EntryId.Length != 0) hash ^= EntryId.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EntryId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntryId);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EntryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntryId);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetEntryStatusRequest other) {
      if (other == null) {
        return;
      }
      if (other.EntryId.Length != 0) {
        EntryId = other.EntryId;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            EntryId = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetEntryStatusResponse : pb::IMessage<GetEntryStatusResponse> {
    private static readonly pb::MessageParser<GetEntryStatusResponse> _parser = new pb::MessageParser<GetEntryStatusResponse>(() => new GetEntryStatusResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetEntryStatusResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Data.Entry.EntryDataReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusResponse(GetEntryStatusResponse other) : this() {
      entryId_ = other.entryId_;
      statusText_ = other.statusText_;
      DeclareDate = other.declareDate_ != null ? other.DeclareDate.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetEntryStatusResponse Clone() {
      return new GetEntryStatusResponse(this);
    }

    /// <summary>Field number for the "entry_id" field.</summary>
    public const int EntryIdFieldNumber = 1;
    private string entryId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string EntryId {
      get { return entryId_; }
      set {
        entryId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "status_text" field.</summary>
    public const int StatusTextFieldNumber = 2;
    private string statusText_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StatusText {
      get { return statusText_; }
      set {
        statusText_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "declare_date" field.</summary>
    public const int DeclareDateFieldNumber = 3;
    private global::Google.Protobuf.WellKnownTypes.Timestamp declareDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DeclareDate {
      get { return declareDate_; }
      set {
        declareDate_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetEntryStatusResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetEntryStatusResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EntryId != other.EntryId) return false;
      if (StatusText != other.StatusText) return false;
      if (!object.Equals(DeclareDate, other.DeclareDate)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EntryId.Length != 0) hash ^= EntryId.GetHashCode();
      if (StatusText.Length != 0) hash ^= StatusText.GetHashCode();
      if (declareDate_ != null) hash ^= DeclareDate.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EntryId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(EntryId);
      }
      if (StatusText.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(StatusText);
      }
      if (declareDate_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DeclareDate);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EntryId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(EntryId);
      }
      if (StatusText.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StatusText);
      }
      if (declareDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DeclareDate);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetEntryStatusResponse other) {
      if (other == null) {
        return;
      }
      if (other.EntryId.Length != 0) {
        EntryId = other.EntryId;
      }
      if (other.StatusText.Length != 0) {
        StatusText = other.StatusText;
      }
      if (other.declareDate_ != null) {
        if (declareDate_ == null) {
          declareDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DeclareDate.MergeFrom(other.DeclareDate);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            EntryId = input.ReadString();
            break;
          }
          case 18: {
            StatusText = input.ReadString();
            break;
          }
          case 26: {
            if (declareDate_ == null) {
              declareDate_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(declareDate_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetYDTEntryDataRequest : pb::IMessage<GetYDTEntryDataRequest> {
    private static readonly pb::MessageParser<GetYDTEntryDataRequest> _parser = new pb::MessageParser<GetYDTEntryDataRequest>(() => new GetYDTEntryDataRequest());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetYDTEntryDataRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Data.Entry.EntryDataReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataRequest(GetYDTEntryDataRequest other) : this() {
      DateFrom = other.dateFrom_ != null ? other.DateFrom.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataRequest Clone() {
      return new GetYDTEntryDataRequest(this);
    }

    /// <summary>Field number for the "date_from" field.</summary>
    public const int DateFromFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp dateFrom_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp DateFrom {
      get { return dateFrom_; }
      set {
        dateFrom_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetYDTEntryDataRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetYDTEntryDataRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(DateFrom, other.DateFrom)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (dateFrom_ != null) hash ^= DateFrom.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (dateFrom_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(DateFrom);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (dateFrom_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DateFrom);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetYDTEntryDataRequest other) {
      if (other == null) {
        return;
      }
      if (other.dateFrom_ != null) {
        if (dateFrom_ == null) {
          dateFrom_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        DateFrom.MergeFrom(other.DateFrom);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (dateFrom_ == null) {
              dateFrom_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(dateFrom_);
            break;
          }
        }
      }
    }

  }

  public sealed partial class GetYDTEntryDataResponse : pb::IMessage<GetYDTEntryDataResponse> {
    private static readonly pb::MessageParser<GetYDTEntryDataResponse> _parser = new pb::MessageParser<GetYDTEntryDataResponse>(() => new GetYDTEntryDataResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetYDTEntryDataResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Etg.Data.Entry.EntryDataReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataResponse(GetYDTEntryDataResponse other) : this() {
      fileName_ = other.fileName_;
      data_ = other.data_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetYDTEntryDataResponse Clone() {
      return new GetYDTEntryDataResponse(this);
    }

    /// <summary>Field number for the "file_name" field.</summary>
    public const int FileNameFieldNumber = 1;
    private string fileName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FileName {
      get { return fileName_; }
      set {
        fileName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetYDTEntryDataResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetYDTEntryDataResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FileName != other.FileName) return false;
      if (Data != other.Data) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (FileName.Length != 0) hash ^= FileName.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (FileName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FileName);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Data);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (FileName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FileName);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetYDTEntryDataResponse other) {
      if (other == null) {
        return;
      }
      if (other.FileName.Length != 0) {
        FileName = other.FileName;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            FileName = input.ReadString();
            break;
          }
          case 18: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
