// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

public final class EtgProto {
  private EtgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etg_auth_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_etg_auth_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_etg_auth_LoginReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_etg_auth_LoginReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\022\010etg.auth\032\rprofile.proto\032\037g" +
      "oogle/protobuf/timestamp.proto\"\273\001\n\014Login" +
      "Request\022\'\n\nlogin_type\030\001 \001(\0162\023.etg.auth.L" +
      "oginType\022\r\n\005email\030\002 \001(\t\022\025\n\rhashed_passwd" +
      "\030\003 \001(\t\022\022\n\ncompany_id\030\004 \001(\t\022\r\n\005token\030\005 \001(" +
      "\t\022\024\n\014access_token\030\006 \001(\t\022\022\n\ncaptcha_id\030\007 " +
      "\001(\t\022\017\n\007captcha\030\010 \001(\t\"\331\001\n\nLoginReply\022\025\n\ri" +
      "s_successful\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\022\024\n\014a" +
      "ccess_token\030\003 \001(\t\0227\n\023timestamp_expire_at" +
      "\030\004 \001(\0132\032.google.protobuf.Timestamp\022&\n\004us",
      "er\030\005 \001(\0132\030.etg.profile.UserProfile\022,\n\007co" +
      "mpany\030\006 \001(\0132\033.etg.profile.CompanyProfile" +
      "*8\n\tLoginType\022\t\n\005EMAIL\020\000\022\016\n\nCOMPANY_ID\020\001" +
      "\022\020\n\014ACCESS_TOKEN\020\002B\'\n\010etg.authB\010EtgProto" +
      "P\001\242\002\003ETG\252\002\010Etg.AuthP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          etg.profile.Profile.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_etg_auth_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_etg_auth_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_etg_auth_LoginRequest_descriptor,
        new java.lang.String[] { "LoginType", "Email", "HashedPasswd", "CompanyId", "Token", "AccessToken", "CaptchaId", "Captcha", });
    internal_static_etg_auth_LoginReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_etg_auth_LoginReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_etg_auth_LoginReply_descriptor,
        new java.lang.String[] { "IsSuccessful", "Message", "AccessToken", "TimestampExpireAt", "User", "Company", });
    etg.profile.Profile.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
