// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

/**
 * Protobuf type {@code etg.auth.LoginRequest}
 */
public  final class LoginRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etg.auth.LoginRequest)
    LoginRequestOrBuilder {
  // Use LoginRequest.newBuilder() to construct.
  private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginRequest() {
    loginType_ = 0;
    email_ = "";
    hashedPasswd_ = "";
    companyId_ = "";
    token_ = "";
    accessToken_ = "";
    captchaId_ = "";
    captcha_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LoginRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            loginType_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            email_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            hashedPasswd_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            companyId_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            token_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            accessToken_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            captchaId_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            captcha_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return etg.auth.EtgProto.internal_static_etg_auth_LoginRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return etg.auth.EtgProto.internal_static_etg_auth_LoginRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            etg.auth.LoginRequest.class, etg.auth.LoginRequest.Builder.class);
  }

  public static final int LOGIN_TYPE_FIELD_NUMBER = 1;
  private int loginType_;
  /**
   * <code>optional .etg.auth.LoginType login_type = 1;</code>
   */
  public int getLoginTypeValue() {
    return loginType_;
  }
  /**
   * <code>optional .etg.auth.LoginType login_type = 1;</code>
   */
  public etg.auth.LoginType getLoginType() {
    etg.auth.LoginType result = etg.auth.LoginType.valueOf(loginType_);
    return result == null ? etg.auth.LoginType.UNRECOGNIZED : result;
  }

  public static final int EMAIL_FIELD_NUMBER = 2;
  private volatile java.lang.Object email_;
  /**
   * <code>optional string email = 2;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <code>optional string email = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HASHED_PASSWD_FIELD_NUMBER = 3;
  private volatile java.lang.Object hashedPasswd_;
  /**
   * <code>optional string hashed_passwd = 3;</code>
   */
  public java.lang.String getHashedPasswd() {
    java.lang.Object ref = hashedPasswd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hashedPasswd_ = s;
      return s;
    }
  }
  /**
   * <code>optional string hashed_passwd = 3;</code>
   */
  public com.google.protobuf.ByteString
      getHashedPasswdBytes() {
    java.lang.Object ref = hashedPasswd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hashedPasswd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COMPANY_ID_FIELD_NUMBER = 4;
  private volatile java.lang.Object companyId_;
  /**
   * <code>optional string company_id = 4;</code>
   */
  public java.lang.String getCompanyId() {
    java.lang.Object ref = companyId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      companyId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string company_id = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCompanyIdBytes() {
    java.lang.Object ref = companyId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      companyId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOKEN_FIELD_NUMBER = 5;
  private volatile java.lang.Object token_;
  /**
   * <pre>
   * token sent to contact's mobile
   * </pre>
   *
   * <code>optional string token = 5;</code>
   */
  public java.lang.String getToken() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      token_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * token sent to contact's mobile
   * </pre>
   *
   * <code>optional string token = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTokenBytes() {
    java.lang.Object ref = token_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      token_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 6;
  private volatile java.lang.Object accessToken_;
  /**
   * <code>optional string access_token = 6;</code>
   */
  public java.lang.String getAccessToken() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessToken_ = s;
      return s;
    }
  }
  /**
   * <code>optional string access_token = 6;</code>
   */
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTCHA_ID_FIELD_NUMBER = 7;
  private volatile java.lang.Object captchaId_;
  /**
   * <code>optional string captcha_id = 7;</code>
   */
  public java.lang.String getCaptchaId() {
    java.lang.Object ref = captchaId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      captchaId_ = s;
      return s;
    }
  }
  /**
   * <code>optional string captcha_id = 7;</code>
   */
  public com.google.protobuf.ByteString
      getCaptchaIdBytes() {
    java.lang.Object ref = captchaId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      captchaId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CAPTCHA_FIELD_NUMBER = 8;
  private volatile java.lang.Object captcha_;
  /**
   * <code>optional string captcha = 8;</code>
   */
  public java.lang.String getCaptcha() {
    java.lang.Object ref = captcha_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      captcha_ = s;
      return s;
    }
  }
  /**
   * <code>optional string captcha = 8;</code>
   */
  public com.google.protobuf.ByteString
      getCaptchaBytes() {
    java.lang.Object ref = captcha_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      captcha_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (loginType_ != etg.auth.LoginType.EMAIL.getNumber()) {
      output.writeEnum(1, loginType_);
    }
    if (!getEmailBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, email_);
    }
    if (!getHashedPasswdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, hashedPasswd_);
    }
    if (!getCompanyIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, companyId_);
    }
    if (!getTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
    }
    if (!getAccessTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, accessToken_);
    }
    if (!getCaptchaIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, captchaId_);
    }
    if (!getCaptchaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, captcha_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (loginType_ != etg.auth.LoginType.EMAIL.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, loginType_);
    }
    if (!getEmailBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, email_);
    }
    if (!getHashedPasswdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, hashedPasswd_);
    }
    if (!getCompanyIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, companyId_);
    }
    if (!getTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
    }
    if (!getAccessTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, accessToken_);
    }
    if (!getCaptchaIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, captchaId_);
    }
    if (!getCaptchaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, captcha_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof etg.auth.LoginRequest)) {
      return super.equals(obj);
    }
    etg.auth.LoginRequest other = (etg.auth.LoginRequest) obj;

    boolean result = true;
    result = result && loginType_ == other.loginType_;
    result = result && getEmail()
        .equals(other.getEmail());
    result = result && getHashedPasswd()
        .equals(other.getHashedPasswd());
    result = result && getCompanyId()
        .equals(other.getCompanyId());
    result = result && getToken()
        .equals(other.getToken());
    result = result && getAccessToken()
        .equals(other.getAccessToken());
    result = result && getCaptchaId()
        .equals(other.getCaptchaId());
    result = result && getCaptcha()
        .equals(other.getCaptcha());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + LOGIN_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + loginType_;
    hash = (37 * hash) + EMAIL_FIELD_NUMBER;
    hash = (53 * hash) + getEmail().hashCode();
    hash = (37 * hash) + HASHED_PASSWD_FIELD_NUMBER;
    hash = (53 * hash) + getHashedPasswd().hashCode();
    hash = (37 * hash) + COMPANY_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCompanyId().hashCode();
    hash = (37 * hash) + TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getToken().hashCode();
    hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccessToken().hashCode();
    hash = (37 * hash) + CAPTCHA_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCaptchaId().hashCode();
    hash = (37 * hash) + CAPTCHA_FIELD_NUMBER;
    hash = (53 * hash) + getCaptcha().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static etg.auth.LoginRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static etg.auth.LoginRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static etg.auth.LoginRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static etg.auth.LoginRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static etg.auth.LoginRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static etg.auth.LoginRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static etg.auth.LoginRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static etg.auth.LoginRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static etg.auth.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static etg.auth.LoginRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(etg.auth.LoginRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etg.auth.LoginRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etg.auth.LoginRequest)
      etg.auth.LoginRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              etg.auth.LoginRequest.class, etg.auth.LoginRequest.Builder.class);
    }

    // Construct using etg.auth.LoginRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      loginType_ = 0;

      email_ = "";

      hashedPasswd_ = "";

      companyId_ = "";

      token_ = "";

      accessToken_ = "";

      captchaId_ = "";

      captcha_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginRequest_descriptor;
    }

    public etg.auth.LoginRequest getDefaultInstanceForType() {
      return etg.auth.LoginRequest.getDefaultInstance();
    }

    public etg.auth.LoginRequest build() {
      etg.auth.LoginRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public etg.auth.LoginRequest buildPartial() {
      etg.auth.LoginRequest result = new etg.auth.LoginRequest(this);
      result.loginType_ = loginType_;
      result.email_ = email_;
      result.hashedPasswd_ = hashedPasswd_;
      result.companyId_ = companyId_;
      result.token_ = token_;
      result.accessToken_ = accessToken_;
      result.captchaId_ = captchaId_;
      result.captcha_ = captcha_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof etg.auth.LoginRequest) {
        return mergeFrom((etg.auth.LoginRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(etg.auth.LoginRequest other) {
      if (other == etg.auth.LoginRequest.getDefaultInstance()) return this;
      if (other.loginType_ != 0) {
        setLoginTypeValue(other.getLoginTypeValue());
      }
      if (!other.getEmail().isEmpty()) {
        email_ = other.email_;
        onChanged();
      }
      if (!other.getHashedPasswd().isEmpty()) {
        hashedPasswd_ = other.hashedPasswd_;
        onChanged();
      }
      if (!other.getCompanyId().isEmpty()) {
        companyId_ = other.companyId_;
        onChanged();
      }
      if (!other.getToken().isEmpty()) {
        token_ = other.token_;
        onChanged();
      }
      if (!other.getAccessToken().isEmpty()) {
        accessToken_ = other.accessToken_;
        onChanged();
      }
      if (!other.getCaptchaId().isEmpty()) {
        captchaId_ = other.captchaId_;
        onChanged();
      }
      if (!other.getCaptcha().isEmpty()) {
        captcha_ = other.captcha_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      etg.auth.LoginRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (etg.auth.LoginRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int loginType_ = 0;
    /**
     * <code>optional .etg.auth.LoginType login_type = 1;</code>
     */
    public int getLoginTypeValue() {
      return loginType_;
    }
    /**
     * <code>optional .etg.auth.LoginType login_type = 1;</code>
     */
    public Builder setLoginTypeValue(int value) {
      loginType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .etg.auth.LoginType login_type = 1;</code>
     */
    public etg.auth.LoginType getLoginType() {
      etg.auth.LoginType result = etg.auth.LoginType.valueOf(loginType_);
      return result == null ? etg.auth.LoginType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .etg.auth.LoginType login_type = 1;</code>
     */
    public Builder setLoginType(etg.auth.LoginType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      loginType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .etg.auth.LoginType login_type = 1;</code>
     */
    public Builder clearLoginType() {
      
      loginType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <code>optional string email = 2;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <code>optional string email = 2;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object hashedPasswd_ = "";
    /**
     * <code>optional string hashed_passwd = 3;</code>
     */
    public java.lang.String getHashedPasswd() {
      java.lang.Object ref = hashedPasswd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hashedPasswd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string hashed_passwd = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHashedPasswdBytes() {
      java.lang.Object ref = hashedPasswd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hashedPasswd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string hashed_passwd = 3;</code>
     */
    public Builder setHashedPasswd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hashedPasswd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string hashed_passwd = 3;</code>
     */
    public Builder clearHashedPasswd() {
      
      hashedPasswd_ = getDefaultInstance().getHashedPasswd();
      onChanged();
      return this;
    }
    /**
     * <code>optional string hashed_passwd = 3;</code>
     */
    public Builder setHashedPasswdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hashedPasswd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object companyId_ = "";
    /**
     * <code>optional string company_id = 4;</code>
     */
    public java.lang.String getCompanyId() {
      java.lang.Object ref = companyId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        companyId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string company_id = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCompanyIdBytes() {
      java.lang.Object ref = companyId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        companyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string company_id = 4;</code>
     */
    public Builder setCompanyId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      companyId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string company_id = 4;</code>
     */
    public Builder clearCompanyId() {
      
      companyId_ = getDefaultInstance().getCompanyId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string company_id = 4;</code>
     */
    public Builder setCompanyIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      companyId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object token_ = "";
    /**
     * <pre>
     * token sent to contact's mobile
     * </pre>
     *
     * <code>optional string token = 5;</code>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        token_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * token sent to contact's mobile
     * </pre>
     *
     * <code>optional string token = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * token sent to contact's mobile
     * </pre>
     *
     * <code>optional string token = 5;</code>
     */
    public Builder setToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      token_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token sent to contact's mobile
     * </pre>
     *
     * <code>optional string token = 5;</code>
     */
    public Builder clearToken() {
      
      token_ = getDefaultInstance().getToken();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * token sent to contact's mobile
     * </pre>
     *
     * <code>optional string token = 5;</code>
     */
    public Builder setTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      token_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accessToken_ = "";
    /**
     * <code>optional string access_token = 6;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string access_token = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string access_token = 6;</code>
     */
    public Builder setAccessToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string access_token = 6;</code>
     */
    public Builder clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string access_token = 6;</code>
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessToken_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object captchaId_ = "";
    /**
     * <code>optional string captcha_id = 7;</code>
     */
    public java.lang.String getCaptchaId() {
      java.lang.Object ref = captchaId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        captchaId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string captcha_id = 7;</code>
     */
    public com.google.protobuf.ByteString
        getCaptchaIdBytes() {
      java.lang.Object ref = captchaId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        captchaId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string captcha_id = 7;</code>
     */
    public Builder setCaptchaId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      captchaId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string captcha_id = 7;</code>
     */
    public Builder clearCaptchaId() {
      
      captchaId_ = getDefaultInstance().getCaptchaId();
      onChanged();
      return this;
    }
    /**
     * <code>optional string captcha_id = 7;</code>
     */
    public Builder setCaptchaIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      captchaId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object captcha_ = "";
    /**
     * <code>optional string captcha = 8;</code>
     */
    public java.lang.String getCaptcha() {
      java.lang.Object ref = captcha_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        captcha_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string captcha = 8;</code>
     */
    public com.google.protobuf.ByteString
        getCaptchaBytes() {
      java.lang.Object ref = captcha_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        captcha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string captcha = 8;</code>
     */
    public Builder setCaptcha(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      captcha_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string captcha = 8;</code>
     */
    public Builder clearCaptcha() {
      
      captcha_ = getDefaultInstance().getCaptcha();
      onChanged();
      return this;
    }
    /**
     * <code>optional string captcha = 8;</code>
     */
    public Builder setCaptchaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      captcha_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:etg.auth.LoginRequest)
  }

  // @@protoc_insertion_point(class_scope:etg.auth.LoginRequest)
  private static final etg.auth.LoginRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new etg.auth.LoginRequest();
  }

  public static etg.auth.LoginRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginRequest>
      PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
    public LoginRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginRequest> getParserForType() {
    return PARSER;
  }

  public etg.auth.LoginRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

