// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

public interface LoginRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etg.auth.LoginRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .etg.auth.LoginType login_type = 1;</code>
   */
  int getLoginTypeValue();
  /**
   * <code>optional .etg.auth.LoginType login_type = 1;</code>
   */
  etg.auth.LoginType getLoginType();

  /**
   * <code>optional string email = 2;</code>
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 2;</code>
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>optional string hashed_passwd = 3;</code>
   */
  java.lang.String getHashedPasswd();
  /**
   * <code>optional string hashed_passwd = 3;</code>
   */
  com.google.protobuf.ByteString
      getHashedPasswdBytes();

  /**
   * <code>optional string company_id = 4;</code>
   */
  java.lang.String getCompanyId();
  /**
   * <code>optional string company_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getCompanyIdBytes();

  /**
   * <pre>
   * token sent to contact's mobile
   * </pre>
   *
   * <code>optional string token = 5;</code>
   */
  java.lang.String getToken();
  /**
   * <pre>
   * token sent to contact's mobile
   * </pre>
   *
   * <code>optional string token = 5;</code>
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>optional string access_token = 6;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>optional string access_token = 6;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>optional string captcha_id = 7;</code>
   */
  java.lang.String getCaptchaId();
  /**
   * <code>optional string captcha_id = 7;</code>
   */
  com.google.protobuf.ByteString
      getCaptchaIdBytes();

  /**
   * <code>optional string captcha = 8;</code>
   */
  java.lang.String getCaptcha();
  /**
   * <code>optional string captcha = 8;</code>
   */
  com.google.protobuf.ByteString
      getCaptchaBytes();
}
