// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

/**
 * Protobuf type {@code etg.auth.LoginReply}
 */
public  final class LoginReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:etg.auth.LoginReply)
    LoginReplyOrBuilder {
  // Use LoginReply.newBuilder() to construct.
  private LoginReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LoginReply() {
    isSuccessful_ = false;
    message_ = "";
    accessToken_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private LoginReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            isSuccessful_ = input.readBool();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            accessToken_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestampExpireAt_ != null) {
              subBuilder = timestampExpireAt_.toBuilder();
            }
            timestampExpireAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestampExpireAt_);
              timestampExpireAt_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            etg.profile.Profile.UserProfile.Builder subBuilder = null;
            if (user_ != null) {
              subBuilder = user_.toBuilder();
            }
            user_ = input.readMessage(etg.profile.Profile.UserProfile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(user_);
              user_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            etg.profile.Profile.CompanyProfile.Builder subBuilder = null;
            if (company_ != null) {
              subBuilder = company_.toBuilder();
            }
            company_ = input.readMessage(etg.profile.Profile.CompanyProfile.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(company_);
              company_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return etg.auth.EtgProto.internal_static_etg_auth_LoginReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return etg.auth.EtgProto.internal_static_etg_auth_LoginReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            etg.auth.LoginReply.class, etg.auth.LoginReply.Builder.class);
  }

  public static final int IS_SUCCESSFUL_FIELD_NUMBER = 1;
  private boolean isSuccessful_;
  /**
   * <code>optional bool is_successful = 1;</code>
   */
  public boolean getIsSuccessful() {
    return isSuccessful_;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <code>optional string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <code>optional string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCESS_TOKEN_FIELD_NUMBER = 3;
  private volatile java.lang.Object accessToken_;
  /**
   * <code>optional string access_token = 3;</code>
   */
  public java.lang.String getAccessToken() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accessToken_ = s;
      return s;
    }
  }
  /**
   * <code>optional string access_token = 3;</code>
   */
  public com.google.protobuf.ByteString
      getAccessTokenBytes() {
    java.lang.Object ref = accessToken_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accessToken_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_EXPIRE_AT_FIELD_NUMBER = 4;
  private com.google.protobuf.Timestamp timestampExpireAt_;
  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  public boolean hasTimestampExpireAt() {
    return timestampExpireAt_ != null;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  public com.google.protobuf.Timestamp getTimestampExpireAt() {
    return timestampExpireAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestampExpireAt_;
  }
  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampExpireAtOrBuilder() {
    return getTimestampExpireAt();
  }

  public static final int USER_FIELD_NUMBER = 5;
  private etg.profile.Profile.UserProfile user_;
  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  public boolean hasUser() {
    return user_ != null;
  }
  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  public etg.profile.Profile.UserProfile getUser() {
    return user_ == null ? etg.profile.Profile.UserProfile.getDefaultInstance() : user_;
  }
  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  public etg.profile.Profile.UserProfileOrBuilder getUserOrBuilder() {
    return getUser();
  }

  public static final int COMPANY_FIELD_NUMBER = 6;
  private etg.profile.Profile.CompanyProfile company_;
  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  public boolean hasCompany() {
    return company_ != null;
  }
  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  public etg.profile.Profile.CompanyProfile getCompany() {
    return company_ == null ? etg.profile.Profile.CompanyProfile.getDefaultInstance() : company_;
  }
  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  public etg.profile.Profile.CompanyProfileOrBuilder getCompanyOrBuilder() {
    return getCompany();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (isSuccessful_ != false) {
      output.writeBool(1, isSuccessful_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    if (!getAccessTokenBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, accessToken_);
    }
    if (timestampExpireAt_ != null) {
      output.writeMessage(4, getTimestampExpireAt());
    }
    if (user_ != null) {
      output.writeMessage(5, getUser());
    }
    if (company_ != null) {
      output.writeMessage(6, getCompany());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (isSuccessful_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, isSuccessful_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    if (!getAccessTokenBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, accessToken_);
    }
    if (timestampExpireAt_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getTimestampExpireAt());
    }
    if (user_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getUser());
    }
    if (company_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getCompany());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof etg.auth.LoginReply)) {
      return super.equals(obj);
    }
    etg.auth.LoginReply other = (etg.auth.LoginReply) obj;

    boolean result = true;
    result = result && (getIsSuccessful()
        == other.getIsSuccessful());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && getAccessToken()
        .equals(other.getAccessToken());
    result = result && (hasTimestampExpireAt() == other.hasTimestampExpireAt());
    if (hasTimestampExpireAt()) {
      result = result && getTimestampExpireAt()
          .equals(other.getTimestampExpireAt());
    }
    result = result && (hasUser() == other.hasUser());
    if (hasUser()) {
      result = result && getUser()
          .equals(other.getUser());
    }
    result = result && (hasCompany() == other.hasCompany());
    if (hasCompany()) {
      result = result && getCompany()
          .equals(other.getCompany());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + IS_SUCCESSFUL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsSuccessful());
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + ACCESS_TOKEN_FIELD_NUMBER;
    hash = (53 * hash) + getAccessToken().hashCode();
    if (hasTimestampExpireAt()) {
      hash = (37 * hash) + TIMESTAMP_EXPIRE_AT_FIELD_NUMBER;
      hash = (53 * hash) + getTimestampExpireAt().hashCode();
    }
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    if (hasCompany()) {
      hash = (37 * hash) + COMPANY_FIELD_NUMBER;
      hash = (53 * hash) + getCompany().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static etg.auth.LoginReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static etg.auth.LoginReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static etg.auth.LoginReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static etg.auth.LoginReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static etg.auth.LoginReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static etg.auth.LoginReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static etg.auth.LoginReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static etg.auth.LoginReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static etg.auth.LoginReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static etg.auth.LoginReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(etg.auth.LoginReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code etg.auth.LoginReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:etg.auth.LoginReply)
      etg.auth.LoginReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              etg.auth.LoginReply.class, etg.auth.LoginReply.Builder.class);
    }

    // Construct using etg.auth.LoginReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      isSuccessful_ = false;

      message_ = "";

      accessToken_ = "";

      if (timestampExpireAtBuilder_ == null) {
        timestampExpireAt_ = null;
      } else {
        timestampExpireAt_ = null;
        timestampExpireAtBuilder_ = null;
      }
      if (userBuilder_ == null) {
        user_ = null;
      } else {
        user_ = null;
        userBuilder_ = null;
      }
      if (companyBuilder_ == null) {
        company_ = null;
      } else {
        company_ = null;
        companyBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return etg.auth.EtgProto.internal_static_etg_auth_LoginReply_descriptor;
    }

    public etg.auth.LoginReply getDefaultInstanceForType() {
      return etg.auth.LoginReply.getDefaultInstance();
    }

    public etg.auth.LoginReply build() {
      etg.auth.LoginReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public etg.auth.LoginReply buildPartial() {
      etg.auth.LoginReply result = new etg.auth.LoginReply(this);
      result.isSuccessful_ = isSuccessful_;
      result.message_ = message_;
      result.accessToken_ = accessToken_;
      if (timestampExpireAtBuilder_ == null) {
        result.timestampExpireAt_ = timestampExpireAt_;
      } else {
        result.timestampExpireAt_ = timestampExpireAtBuilder_.build();
      }
      if (userBuilder_ == null) {
        result.user_ = user_;
      } else {
        result.user_ = userBuilder_.build();
      }
      if (companyBuilder_ == null) {
        result.company_ = company_;
      } else {
        result.company_ = companyBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof etg.auth.LoginReply) {
        return mergeFrom((etg.auth.LoginReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(etg.auth.LoginReply other) {
      if (other == etg.auth.LoginReply.getDefaultInstance()) return this;
      if (other.getIsSuccessful() != false) {
        setIsSuccessful(other.getIsSuccessful());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (!other.getAccessToken().isEmpty()) {
        accessToken_ = other.accessToken_;
        onChanged();
      }
      if (other.hasTimestampExpireAt()) {
        mergeTimestampExpireAt(other.getTimestampExpireAt());
      }
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (other.hasCompany()) {
        mergeCompany(other.getCompany());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      etg.auth.LoginReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (etg.auth.LoginReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private boolean isSuccessful_ ;
    /**
     * <code>optional bool is_successful = 1;</code>
     */
    public boolean getIsSuccessful() {
      return isSuccessful_;
    }
    /**
     * <code>optional bool is_successful = 1;</code>
     */
    public Builder setIsSuccessful(boolean value) {
      
      isSuccessful_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional bool is_successful = 1;</code>
     */
    public Builder clearIsSuccessful() {
      
      isSuccessful_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <code>optional string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <code>optional string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object accessToken_ = "";
    /**
     * <code>optional string access_token = 3;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string access_token = 3;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string access_token = 3;</code>
     */
    public Builder setAccessToken(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      accessToken_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string access_token = 3;</code>
     */
    public Builder clearAccessToken() {
      
      accessToken_ = getDefaultInstance().getAccessToken();
      onChanged();
      return this;
    }
    /**
     * <code>optional string access_token = 3;</code>
     */
    public Builder setAccessTokenBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      accessToken_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestampExpireAt_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampExpireAtBuilder_;
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public boolean hasTimestampExpireAt() {
      return timestampExpireAtBuilder_ != null || timestampExpireAt_ != null;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public com.google.protobuf.Timestamp getTimestampExpireAt() {
      if (timestampExpireAtBuilder_ == null) {
        return timestampExpireAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestampExpireAt_;
      } else {
        return timestampExpireAtBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public Builder setTimestampExpireAt(com.google.protobuf.Timestamp value) {
      if (timestampExpireAtBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestampExpireAt_ = value;
        onChanged();
      } else {
        timestampExpireAtBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public Builder setTimestampExpireAt(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampExpireAtBuilder_ == null) {
        timestampExpireAt_ = builderForValue.build();
        onChanged();
      } else {
        timestampExpireAtBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public Builder mergeTimestampExpireAt(com.google.protobuf.Timestamp value) {
      if (timestampExpireAtBuilder_ == null) {
        if (timestampExpireAt_ != null) {
          timestampExpireAt_ =
            com.google.protobuf.Timestamp.newBuilder(timestampExpireAt_).mergeFrom(value).buildPartial();
        } else {
          timestampExpireAt_ = value;
        }
        onChanged();
      } else {
        timestampExpireAtBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public Builder clearTimestampExpireAt() {
      if (timestampExpireAtBuilder_ == null) {
        timestampExpireAt_ = null;
        onChanged();
      } else {
        timestampExpireAt_ = null;
        timestampExpireAtBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampExpireAtBuilder() {
      
      onChanged();
      return getTimestampExpireAtFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampExpireAtOrBuilder() {
      if (timestampExpireAtBuilder_ != null) {
        return timestampExpireAtBuilder_.getMessageOrBuilder();
      } else {
        return timestampExpireAt_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestampExpireAt_;
      }
    }
    /**
     * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampExpireAtFieldBuilder() {
      if (timestampExpireAtBuilder_ == null) {
        timestampExpireAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestampExpireAt(),
                getParentForChildren(),
                isClean());
        timestampExpireAt_ = null;
      }
      return timestampExpireAtBuilder_;
    }

    private etg.profile.Profile.UserProfile user_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        etg.profile.Profile.UserProfile, etg.profile.Profile.UserProfile.Builder, etg.profile.Profile.UserProfileOrBuilder> userBuilder_;
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public boolean hasUser() {
      return userBuilder_ != null || user_ != null;
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public etg.profile.Profile.UserProfile getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? etg.profile.Profile.UserProfile.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public Builder setUser(etg.profile.Profile.UserProfile value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
        onChanged();
      } else {
        userBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public Builder setUser(
        etg.profile.Profile.UserProfile.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
        onChanged();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public Builder mergeUser(etg.profile.Profile.UserProfile value) {
      if (userBuilder_ == null) {
        if (user_ != null) {
          user_ =
            etg.profile.Profile.UserProfile.newBuilder(user_).mergeFrom(value).buildPartial();
        } else {
          user_ = value;
        }
        onChanged();
      } else {
        userBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public Builder clearUser() {
      if (userBuilder_ == null) {
        user_ = null;
        onChanged();
      } else {
        user_ = null;
        userBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public etg.profile.Profile.UserProfile.Builder getUserBuilder() {
      
      onChanged();
      return getUserFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    public etg.profile.Profile.UserProfileOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            etg.profile.Profile.UserProfile.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>optional .etg.profile.UserProfile user = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        etg.profile.Profile.UserProfile, etg.profile.Profile.UserProfile.Builder, etg.profile.Profile.UserProfileOrBuilder> 
        getUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            etg.profile.Profile.UserProfile, etg.profile.Profile.UserProfile.Builder, etg.profile.Profile.UserProfileOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private etg.profile.Profile.CompanyProfile company_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        etg.profile.Profile.CompanyProfile, etg.profile.Profile.CompanyProfile.Builder, etg.profile.Profile.CompanyProfileOrBuilder> companyBuilder_;
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public boolean hasCompany() {
      return companyBuilder_ != null || company_ != null;
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public etg.profile.Profile.CompanyProfile getCompany() {
      if (companyBuilder_ == null) {
        return company_ == null ? etg.profile.Profile.CompanyProfile.getDefaultInstance() : company_;
      } else {
        return companyBuilder_.getMessage();
      }
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public Builder setCompany(etg.profile.Profile.CompanyProfile value) {
      if (companyBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        company_ = value;
        onChanged();
      } else {
        companyBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public Builder setCompany(
        etg.profile.Profile.CompanyProfile.Builder builderForValue) {
      if (companyBuilder_ == null) {
        company_ = builderForValue.build();
        onChanged();
      } else {
        companyBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public Builder mergeCompany(etg.profile.Profile.CompanyProfile value) {
      if (companyBuilder_ == null) {
        if (company_ != null) {
          company_ =
            etg.profile.Profile.CompanyProfile.newBuilder(company_).mergeFrom(value).buildPartial();
        } else {
          company_ = value;
        }
        onChanged();
      } else {
        companyBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public Builder clearCompany() {
      if (companyBuilder_ == null) {
        company_ = null;
        onChanged();
      } else {
        company_ = null;
        companyBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public etg.profile.Profile.CompanyProfile.Builder getCompanyBuilder() {
      
      onChanged();
      return getCompanyFieldBuilder().getBuilder();
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    public etg.profile.Profile.CompanyProfileOrBuilder getCompanyOrBuilder() {
      if (companyBuilder_ != null) {
        return companyBuilder_.getMessageOrBuilder();
      } else {
        return company_ == null ?
            etg.profile.Profile.CompanyProfile.getDefaultInstance() : company_;
      }
    }
    /**
     * <code>optional .etg.profile.CompanyProfile company = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        etg.profile.Profile.CompanyProfile, etg.profile.Profile.CompanyProfile.Builder, etg.profile.Profile.CompanyProfileOrBuilder> 
        getCompanyFieldBuilder() {
      if (companyBuilder_ == null) {
        companyBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            etg.profile.Profile.CompanyProfile, etg.profile.Profile.CompanyProfile.Builder, etg.profile.Profile.CompanyProfileOrBuilder>(
                getCompany(),
                getParentForChildren(),
                isClean());
        company_ = null;
      }
      return companyBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:etg.auth.LoginReply)
  }

  // @@protoc_insertion_point(class_scope:etg.auth.LoginReply)
  private static final etg.auth.LoginReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new etg.auth.LoginReply();
  }

  public static etg.auth.LoginReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LoginReply>
      PARSER = new com.google.protobuf.AbstractParser<LoginReply>() {
    public LoginReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new LoginReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LoginReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LoginReply> getParserForType() {
    return PARSER;
  }

  public etg.auth.LoginReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

