// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

public interface LoginReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:etg.auth.LoginReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bool is_successful = 1;</code>
   */
  boolean getIsSuccessful();

  /**
   * <code>optional string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>optional string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>optional string access_token = 3;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>optional string access_token = 3;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  boolean hasTimestampExpireAt();
  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  com.google.protobuf.Timestamp getTimestampExpireAt();
  /**
   * <code>optional .google.protobuf.Timestamp timestamp_expire_at = 4;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampExpireAtOrBuilder();

  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  boolean hasUser();
  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  etg.profile.Profile.UserProfile getUser();
  /**
   * <code>optional .etg.profile.UserProfile user = 5;</code>
   */
  etg.profile.Profile.UserProfileOrBuilder getUserOrBuilder();

  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  boolean hasCompany();
  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  etg.profile.Profile.CompanyProfile getCompany();
  /**
   * <code>optional .etg.profile.CompanyProfile company = 6;</code>
   */
  etg.profile.Profile.CompanyProfileOrBuilder getCompanyOrBuilder();
}
