// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package etg.auth;

/**
 * Protobuf enum {@code etg.auth.LoginType}
 */
public enum LoginType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>EMAIL = 0;</code>
   */
  EMAIL(0),
  /**
   * <code>COMPANY_ID = 1;</code>
   */
  COMPANY_ID(1),
  /**
   * <code>ACCESS_TOKEN = 2;</code>
   */
  ACCESS_TOKEN(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>EMAIL = 0;</code>
   */
  public static final int EMAIL_VALUE = 0;
  /**
   * <code>COMPANY_ID = 1;</code>
   */
  public static final int COMPANY_ID_VALUE = 1;
  /**
   * <code>ACCESS_TOKEN = 2;</code>
   */
  public static final int ACCESS_TOKEN_VALUE = 2;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LoginType valueOf(int value) {
    return forNumber(value);
  }

  public static LoginType forNumber(int value) {
    switch (value) {
      case 0: return EMAIL;
      case 1: return COMPANY_ID;
      case 2: return ACCESS_TOKEN;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LoginType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LoginType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LoginType>() {
          public LoginType findValueByNumber(int number) {
            return LoginType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return etg.auth.EtgProto.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final LoginType[] VALUES = values();

  public static LoginType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LoginType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:etg.auth.LoginType)
}

